### ISSUE TITLE
Won't control unless Corsair service is running

### ISSUE THREAD

**Issue by ZetsumeiIkari** [EvanMulawski/FanControl.CorsairLink#102]
without the "Corsiar service" running FanControl doesn't seem to be able to control the CPU FANs and they just get set to full.

**Comment by ZetsumeiIkari** [comment]
I'm using a H100i Platinum

**Comment by EvanMulawski** [comment]
Hi @ZetsumeiIkari, can you attach the CorsairLink.log file located in the Fan Control directory and a screenshot of Fan Control's Home tab?

**Comment by ZetsumeiIkari** [comment]
[CorsairLink.log](https://github.com/EvanMulawski/FanControl.CorsairLink/files/12643893/CorsairLink.log)

**Comment by ZetsumeiIkari** [comment]
Currently its working with, icue closed, all the corsiar services stopped/disabled expect Corsiar service. after a while i hear the windows device disconnected sound and the CPU fans go full until the  corsiar service is restared

**Comment by EvanMulawski** [comment]
That shouldn't be happening and the Corsair Service is definitely not required for this plugin to function. Can you stop Corsair Service, set the `FANCONTROL_CORSAIRLINK_DEBUG_LOGGING_ENABLED` [environment variable](#78) to `1`, restart Fan Control, wait five minutes, and post the CorsairLink.log file again?

**Comment by ZetsumeiIkari** [comment]
Here you go
[CorsairLink.log](https://github.com/EvanMulawski/FanControl.CorsairLink/files/12676509/CorsairLink.log)

**Comment by ZetsumeiIkari** [comment]
[CorsairLink.log](https://github.com/EvanMulawski/FanControl.CorsairLink/files/12678414/CorsairLink.log)

**Comment by EvanMulawski** [comment]
@ZetsumeiIkari Please try the attached build, ensure debug logging is enabled as mentioned above, and post the CorsairLink.log file after testing.

[FanControl.CorsairLink-HydroPlatinumControlIssues-v20230922r001.zip](https://github.com/EvanMulawski/FanControl.CorsairLink/files/12705356/FanControl.CorsairLink-HydroPlatinumControlIssues-v20230922r001.zip)

**Comment by ZetsumeiIkari** [comment]
No change, here is the log 
[CorsairLink.log](https://github.com/EvanMulawski/FanControl.CorsairLink/files/12741914/CorsairLink.log)
[log.txt](https://github.com/EvanMulawski/FanControl.CorsairLink/files/12741917/log.txt)

**Comment by EvanMulawski** [comment]
@ZetsumeiIkari Please try both of the builds here and provide the CorsairLink.log file after testing:

https://github.com/EvanMulawski/FanControl.CorsairLink/issues/104#issuecomment-1732637454

**Comment by ZetsumeiIkari** [comment]
yes v20230924r001 works for me with the service off, see attached logs

[CorsairLink-v20230924r002-notworking.log](https://github.com/EvanMulawski/FanControl.CorsairLink/files/12754463/CorsairLink-v20230924r002-notworking.log)
[CorsairLink-v20230924r001-working.log](https://github.com/EvanMulawski/FanControl.CorsairLink/files/12754464/CorsairLink-v20230924r001-working.log)

**Comment by ZetsumeiIkari** [comment]
Thanks for your help i'll keep you updated if anything changes.

**Comment by EvanMulawski** [comment]
@ZetsumeiIkari Can you confirm this build is working before I release it as v1.4.1? Thanks!

[FanControl.CorsairLink-HydroPlatinumControlIssues-v20230929r001.zip](https://github.com/EvanMulawski/FanControl.CorsairLink/files/12772123/FanControl.CorsairLink-HydroPlatinumControlIssues-v20230929r001.zip)

**Comment by ZetsumeiIkari** [comment]
Yeah, that build is working.

**Comment by EvanMulawski** [comment]
Fixed in [v1.4.1](https://github.com/EvanMulawski/FanControl.CorsairLink/releases/tag/v1.4.1)
