### ISSUE TITLE
Can't control fan speed of H100i PRO XT (RGB Version)

### ISSUE THREAD

**Issue by AreskiS** [EvanMulawski/FanControl.CorsairLink#104]
![image](https://github.com/EvanMulawski/FanControl.CorsairLink/assets/145702997/5eb97ef2-f68c-4c68-b593-69c2bc8b255c)

Im nez to FanControl so It might just be an user issue ^^

Also can't control pump but I dont mind

**Comment by AreskiS** [comment]
[CorsairLink.log](https://github.com/EvanMulawski/FanControl.CorsairLink/files/12689531/CorsairLink.log)

**Comment by EvanMulawski** [comment]
Hi @AreskiS, can you set the `FANCONTROL_CORSAIRLINK_DEBUG_LOGGING_ENABLED` [environment variable](#78) to `1`, restart Fan Control, change the speed sliders, and post the CorsairLink.log file again? Thanks!

**Comment by AreskiS** [comment]
How can I do that ? I dont find a config file or something with this variable :/

**Comment by AreskiS** [comment]
I did "set FANCONTROL_CORSAIRLINK_DEBUG_LOGGING_ENABLED=1" in a cmd but the log are still only at info state

**Comment by EvanMulawski** [comment]
@AreskiS Please try the attached build, ensure debug logging is enabled as mentioned above, and post the CorsairLink.log file after testing.

[FanControl.CorsairLink-HydroPlatinumControlIssues-v20230922r001.zip](https://github.com/EvanMulawski/FanControl.CorsairLink/files/12705360/FanControl.CorsairLink-HydroPlatinumControlIssues-v20230922r001.zip)

**Comment by AreskiS** [comment]
Still the same, here's the log file 
[CorsairLink.log](https://github.com/EvanMulawski/FanControl.CorsairLink/files/12705890/CorsairLink.log)

**Comment by EvanMulawski** [comment]
@AreskiS New build.

[FanControl.CorsairLink-HydroPlatinumControlIssues-v20230923r001.zip](https://github.com/EvanMulawski/FanControl.CorsairLink/files/12707202/FanControl.CorsairLink-HydroPlatinumControlIssues-v20230923r001.zip)

**Comment by AreskiS** [comment]
![Screenshot 2023-09-24 011407](https://github.com/EvanMulawski/FanControl.CorsairLink/assets/145702997/6900ef19-40fc-4abc-8bbe-58d90305722b)
![Screenshot 2023-09-24 011431](https://github.com/EvanMulawski/FanControl.CorsairLink/assets/145702997/6284f0e3-ca9d-4b58-b9f5-87a3f5951845)
![Screenshot 2023-09-24 011449](https:/
[CorsairLink.log](https://github.com/EvanMulawski/FanControl.CorsairLink/files/12707434/CorsairLink.log)
/github.com/EvanMulawski/FanCo
[Corsair logs too long.txt](https://github.com/EvanMulawski/FanControl.CorsairLink/files/12707436/Corsair.logs.too.long.txt)
ntrol.CorsairLink/assets/145702997/56de7ea3-d672-4be4-a511-e8e41180f35a)[CorsairLink.1.log](https://github.com/EvanMulawski/FanControl.CorsairLink/files/12707428/CorsairLink.1.log)
[log.txt](https://github.com/EvanMulawski/FanControl.CorsairLink/files/12707429/log.txt)

**Comment by EvanMulawski** [comment]
@AreskiS New build.

[FanControl.CorsairLink-HydroPlatinumControlIssues-v20230923r002.zip](https://github.com/EvanMulawski/FanControl.CorsairLink/files/12707466/FanControl.CorsairLink-HydroPlatinumControlIssues-v20230923r002.zip)

**Comment by AreskiS** [comment]
I dont know what you did but its working great 
Thanks a lot you're the best

**Comment by EvanMulawski** [comment]
@AreskiS Can you delete your current CorsairLink.log files, restart Fan Control, and upload a new log file (with debug logging enabled)? Thanks!

**Comment by AreskiS** [comment]
Sure here you go >
[CorsairLink.log](https://github.com/EvanMulawski/FanControl.CorsairLink/files/12709280/CorsairLink.log)

**Comment by EvanMulawski** [comment]
@AreskiS Would you mind testing these two builds? I changed two things in the build that is working for you but now I need to know which change was actually needed. Please post the log file after testing both.

[FanControl.CorsairLink-HydroPlatinumControlIssues-v20230924r001.zip](https://github.com/EvanMulawski/FanControl.CorsairLink/files/12709347/FanControl.CorsairLink-HydroPlatinumControlIssues-v20230924r001.zip)
[FanControl.CorsairLink-HydroPlatinumControlIssues-v20230924r002.zip](https://github.com/EvanMulawski/FanControl.CorsairLink/files/12709348/FanControl.CorsairLink-HydroPlatinumControlIssues-v20230924r002.zip)

**Comment by AreskiS** [comment]
I'll do it in 2 days I will not have acces to my computer before but sure will do

**Comment by ZetsumeiIkari** [comment]
Here are my results, v20230924r001 is working for me I'll attach logs
[CorsairLink-v20230924r001-working.log](https://github.com/EvanMulawski/FanControl.CorsairLink/files/12754461/CorsairLink-v20230924r001-working.log)
[CorsairLink-v20230924r002-notworking.log](https://github.com/EvanMulawski/FanControl.CorsairLink/files/12754462/CorsairLink-v20230924r002-notworking.log)

**Comment by AreskiS** [comment]
Here are my results aswell >
[CorsairLinkFix001.log](https://github.com/EvanMulawski/FanControl.CorsairLink/files/12757773/CorsairLinkFix001.log)
[CorsairLinkFix002.log](https://github.com/EvanMulawski/FanControl.CorsairLink/files/12757782/CorsairLinkFix002.log)

001 Working
002 Not Working

**Comment by EvanMulawski** [comment]
@AreskiS Can you confirm this build is working before I release it as v1.4.1? Thanks!

[FanControl.CorsairLink-HydroPlatinumControlIssues-v20230929r001.zip](https://github.com/EvanMulawski/FanControl.CorsairLink/files/12772142/FanControl.CorsairLink-HydroPlatinumControlIssues-v20230929r001.zip)

**Comment by EvanMulawski** [comment]
Fixed in [v1.4.1](https://github.com/EvanMulawski/FanControl.CorsairLink/releases/tag/v1.4.1)
