### ISSUE TITLE
Corsair h115i pro xt, CorsairLink could not initialize or has no sensors

### ISSUE THREAD

**Issue by EndangeredPanda** [EvanMulawski/FanControl.CorsairLink#105]
Upon app startup with plugin installed this is the only message I receive it is then followed by a mulitiple errors detected popup
[CorsairLink.log](https://github.com/EvanMulawski/FanControl.CorsairLink/files/12703976/CorsairLink.log)

**Comment by EvanMulawski** [comment]
Hi @EndangeredPanda, the "A device attached to the system is not functioning" error usually indicates one of the following:

- there is a problem with the USB connection
- not enough power is supplied to the device
- the device is malfunctioning

Ensure the device is listed as connected in Device Manager and/or [USBDeview](https://www.nirsoft.net/utils/usbdeview-x64.zip).

**Comment by EndangeredPanda** [comment]
Solved it I plugged it into a internal powered usb hub and now its working fine.
