### ISSUE TITLE
H100i Elite RGB : System.IO.IOException An error occurred refreshing device 'CORSAIR iCUE Commander CORE

### ISSUE THREAD

**Issue by Artoriasx96** [EvanMulawski/FanControl.CorsairLink#107]
Randomly system locks up, mouse included and have to unplug from USB port and plug again for it to work. Commander Core RGB also turns off. Seems to happen during heavy gaming use, not very frequently but at least once a day.
It didn't happen on previous builds of Fan Control but lately it has been happening to the point that I don't know what could be causing it.
I upload here the two logs that I have in case it helps to solve the issue. Thank you for your work. Love this plugin.

PS: I don't have any RGB control software running on the background, only set up a static color at startup through OpenRGB command line, so nothing running in the background that could cause this as far as I'm aware.

[CorsairLink.log](https://github.com/EvanMulawski/FanControl.CorsairLink/files/12825256/CorsairLink.log)
[log.txt](https://github.com/EvanMulawski/FanControl.CorsairLink/files/12825257/log.txt)

**Comment by EvanMulawski** [comment]
This looks like an issue with the USB Controller - especially the second occurrence in the log where the device essentially disappeared from the system.

Are you running an AMD or Intel system? Ensure your BIOS is up-to-date and try using a different USB header on your motherboard.

**Comment by Artoriasx96** [comment]
So far I've isolated the issue to the USB controller of the mouse, I have moved it into the front panel USB and there's no more USB controller crashes, is quite strange. Will update if I find an exact answer.
