### ISSUE TITLE
How can I install this plugin?

### ISSUE THREAD

**Issue by GalGreenfield** [EvanMulawski/FanControl.CorsairLink#109]
I just downloaded and installed the latest FanControl version, v177. How can I install this plugin?
The `Plugins` directory is missing, and even though I created it manually after installing FanControl, it's still not loading the plugin. So I'm not sure if it's a problem with FC, me not following the steps correctly or with the plugin.

**Comment by DfrostX** [comment]
@GalGreenfield 

Latest FanControl is 171, not 177

About your issue. Yes, you needed to created the folder manually, its not there by default

Make sure you did not forget a step from the install readme https://github.com/EvanMulawski/FanControl.CorsairLink#installation, especially the net 4.8 and the unblock parts

Once done, go in fancontrol, section "settings", sub section sensors "edit sources" and make sure CorsairLink in ticked. If not, tick it and restart FanControl

Other than that, im not sure

**Comment by EvanMulawski** [comment]
Feel free to reopen if this is not resolved.
