### ISSUE TITLE
Corsair Commander Core Plugin won't allow for 0% fan control

### ISSUE THREAD

**Issue by wsm78** [EvanMulawski/FanControl.CorsairLink#110]
See https://github.com/Rem0o/FanControl.Releases/issues/2078

Describe the bug
See title - and when attempting zero percent I get plenty of error popups. The RPMs do decrease but not to zero, and did make sure to exclude any and all rgb/fan control software besides this one.

Is there a log.txt file next to FanControl.exe with recent date entries?
log.txt

Relevant hardware specs and setup
Two Commander Cores with all fans/RGB connected into it (excluding GPU and RAM)

**Comment by wsm78** [comment]
Referenced https://github.com/EvanMulawski/FanControl.CorsairLink/issues/90#issuecomment-1703244115 as it seems this was tackled before. I tried the beta version and still cannot hit 0 RPM. 600-700 consistently.

**Comment by wsm78** [comment]
Updated logs:
[log.txt](https://github.com/EvanMulawski/FanControl.CorsairLink/files/12861565/log.txt)
[CorsairLink - Copy.txt](https://github.com/EvanMulawski/FanControl.CorsairLink/files/12861569/CorsairLink.-.Copy.txt)

**Comment by wsm78** [comment]
Fixed with rescan of sensors. I am running into another issue however where the pump cannot be controlled (I have a h150i elite lcd)? No errors it looks -
[log.txt](https://github.com/EvanMulawski/FanControl.CorsairLink/files/12861805/log.txt)

**Comment by wsm78** [comment]
Disregard as well - figured out which is the pump, although not able to hit zero RPM, which I think is expected since the AIO pump fan can't go 0 in icue, right?

**Comment by EvanMulawski** [comment]
Hi @wsm78,

- v1.4.1 is the latest version of this plugin and includes any fixes made in previous beta releases.
- I'm not sure if the pump can be set to 0 rpm - I will check and get back to you.
- Some fans do not support 0 rpm - they have a minimum speed.
- For the AX-series PSU, you will need to install the driver included in the plugin download. ([Instructions](https://github.com/EvanMulawski/FanControl.CorsairLink#siusbxpress-driver))

**Comment by wsm78** [comment]
Sure! Also - do you know just as a general bit how to set a mix fan curve where it would use either a user-defined CPU curve or the default GPU curve depending on CPU/GPU temps? I can do mixed with two customs but wanted to see if I could just rely on the default settings of my GPU AIO

**Comment by wsm78** [comment]
@EvanMulawski Hmm I'm still getting 0% even when manually tuning even with latest version:
![image](https://github.com/EvanMulawski/FanControl.CorsairLink/assets/92889018/0284fc9d-5a5f-40a7-b816-2268909917d3)

**Comment by wsm78** [comment]
It is to note all of these can do zero RPM in icue. They're all ML120s.

**Comment by wsm78** [comment]
Bit early to say - it looks like it's because I had SignalRGB open at the same time. Wasn't there compatibility between the two?

**Comment by EvanMulawski** [comment]
> I had SignalRGB open at the same time. Wasn't there compatibility between the two?

SignalRGB v2.2.29 and above is compatible, but the fan control feature has to be disabled on the device if you have the Pro version.

**Comment by EvanMulawski** [comment]
Feel free to reopen if this is not resolved.
