### ISSUE TITLE
Support for iCUE LINK products 

### ISSUE THREAD

**Issue by a-zndr** [EvanMulawski/FanControl.CorsairLink#111]
I see you're lacking support for the new iCue link products. I have the following and I'm happy to help with any info/testing if needed.

- iCUE LINK QX140 RGB
- iCUE LINK QX120 RGB
- iCUE Link H100i RGB Liquid CPU Cooler (in my case the 240)

I know there were issues with the old hub, but not sure if the newer (small) hub and fans have the same problem.

**Comment by EvanMulawski** [comment]
Related to #86

**Comment by a-zndr** [comment]
added a pcap to that issue. Thanks @EvanMulawski

**Comment by EvanMulawski** [comment]
@a-zndr @IssacI19 @vladimirgluten @MaxManYT @ScoPeZs @jhiggins 

A build with iCUE LINK support is attached. Please follow the usual update/installation process and test without iCUE/SignalRGB running (also stop any running Corsair services). Comment here with your newest CorsairLink.log file attached.

[FanControl.CorsairLink-iCUELINKSupport-v20231126r001.zip](https://github.com/EvanMulawski/FanControl.CorsairLink/files/13465988/FanControl.CorsairLink-iCUELINKSupport-v20231126r001.zip)

**Comment by a-zndr** [comment]
@EvanMulawski Unfortunately I cannot get the plugin to load

`CorsairLink could not initialize or has no sensors`

No icue/corsair/rgb services are running. Tried a system restart, there are no other plugins,

**Comment by EvanMulawski** [comment]
@a-zndr Can you attach the CorsairLink.log files located in the Fan Control directory? Thanks!

**Comment by a-zndr** [comment]
@EvanMulawski oh yeah duh 
[CorsairLink.log](https://github.com/EvanMulawski/FanControl.CorsairLink/files/13469076/CorsairLink.log)

**Comment by EvanMulawski** [comment]
@a-zndr New build. See https://github.com/EvanMulawski/FanControl.CorsairLink/issues/111#issuecomment-1826597906

**Comment by EvanMulawski** [comment]
@a-zndr Log file appears to be empty? No need for the SiUsbXpress driver - not needed for this device.

**Comment by nicksmith26262626** [comment]
@EvanMulawski 
[CorsairLink.log](https://github.com/EvanMulawski/FanControl.CorsairLink/files/13482277/CorsairLink.log)

**Comment by EvanMulawski** [comment]
New build [available](https://github.com/EvanMulawski/FanControl.CorsairLink/issues/111#issuecomment-1826597906). I don't expect it to work but I need to see the log.

**Comment by jhiggins** [comment]
> New build [available](https://github.com/EvanMulawski/FanControl.CorsairLink/issues/111#issuecomment-1826597906). I don't expect it to work but I need to see the log.

I’m traveling for the next week, but I’ll gladly catch up and try these out when I’m back in town

**Comment by a-zndr** [comment]
[CorsairLink.log](https://github.com/EvanMulawski/FanControl.CorsairLink/files/13483435/CorsairLink.log)

**Comment by EvanMulawski** [comment]
New build [available](https://github.com/EvanMulawski/FanControl.CorsairLink/issues/111#issuecomment-1826597906).

**Comment by a-zndr** [comment]
[CorsairLink.log](https://github.com/EvanMulawski/FanControl.CorsairLink/files/13483955/CorsairLink.log)

**Comment by EvanMulawski** [comment]
New build [available](https://github.com/EvanMulawski/FanControl.CorsairLink/issues/111#issuecomment-1826597906).

**Comment by EvanMulawski** [comment]
New build [available](https://github.com/EvanMulawski/FanControl.CorsairLink/issues/111#issuecomment-1826597906).

**Comment by a-zndr** [comment]
WOAH no error and I see lots of sensors!!!!!
[CorsairLink.log](https://github.com/EvanMulawski/FanControl.CorsairLink/files/13494862/CorsairLink.log)
<img width="342" alt="Screenshot 2023-11-28 165214" src="https://github.com/EvanMulawski/FanControl.CorsairLink/assets/14003031/9273b5cb-76bb-44dc-a16b-4720bf94e983">

**Comment by EvanMulawski** [comment]
New build [available](https://github.com/EvanMulawski/FanControl.CorsairLink/issues/111#issuecomment-1826597906).

Should be very close now!

**Comment by a-zndr** [comment]
We have fans and pumps! No control yet but I SEE EM
<img width="1476" alt="Screenshot 2023-11-28 190532" src="https://github.com/EvanMulawski/FanControl.CorsairLink/assets/14003031/f535fd8b-574c-418d-93aa-d92f57779570">
[Uploading CorsairLink.1.log…]()

**Comment by EvanMulawski** [comment]
@a-zndr Can you fix the log file upload? Thanks!

**Comment by a-zndr** [comment]
[CorsairLink.1.log](https://github.com/EvanMulawski/FanControl.CorsairLink/files/13495940/CorsairLink.1.log)

**Comment by EvanMulawski** [comment]
New build [available](https://github.com/EvanMulawski/FanControl.CorsairLink/issues/111#issuecomment-1826597906).

**Comment by a-zndr** [comment]
[Uploading CorsairLink.2.log…]()

**Comment by a-zndr** [comment]
[CorsairLink.2.log](https://github.com/EvanMulawski/FanControl.CorsairLink/files/13496379/CorsairLink.2.log)

**Comment by EvanMulawski** [comment]
@a-zndr Looks like the fan/pump control is working. Anything not working for you?

**Comment by nicksmith26262626** [comment]
@EvanMulawski Everything works for me except for the H150i pump. Thanks for adding support for the fans!
[CorsairLink.log](https://github.com/EvanMulawski/FanControl.CorsairLink/files/13496612/CorsairLink.log)

**Comment by EvanMulawski** [comment]
@nicksmith26262626 It looks like your pump is responding to control based on the logs. Can you detail the issue you're having?

**Comment by a-zndr** [comment]
Everything is working here as well, though it didn't on first load which was weird. But restarting the app everything is perfect including the pump. Now I just have to set all new curves!

**Comment by EvanMulawski** [comment]
@a-zndr I would be interested in knowing if SignalRGB (which supports iCUE LINK) works concurrently if you want to give that a try.

**Comment by nicksmith26262626** [comment]
@EvanMulawski  Sorry its working! Just had to pair it manually.  Thank you! Also, I'm running SignalRGB right now with no issues.

**Comment by a-zndr** [comment]
> @a-zndr I would be interested in knowing if SignalRGB (which supports iCUE LINK) works concurrently if you want to give that a try.

I didn't see it on their supported site, I'll give it a try

**Comment by nicksmith26262626** [comment]
@EvanMulawski Actually theres a litte bit of lag on Signal RGB. It kind of skips a little bit

**Comment by a-zndr** [comment]
@nicksmith26262626 yeah I can get mine to work, but it sees all of the icue link stuff as a single device right now. Not sure if that's because I don't pay for it

**Comment by nicksmith26262626** [comment]
I've got the pro version, and in the devices tab its always showed up as one device. But on the layouts tab all of the fans show up as separate devices

**Comment by a-zndr** [comment]
> I've got the pro version, and in the devices tab its always showed up as one device. But on the layouts tab all of the fans show up as separate devices

I'm dumb there's a drop down I didn't see! ok I'll fiddle with this thanks @nicksmith26262626

**Comment by a-zndr** [comment]
Oh I see what you mean now about the "lag" it definitely stutters a bit

**Comment by EvanMulawski** [comment]
@ScoPeZs You might need to pair the pump control with the speed sensor manually (click the three dot menu button on the pump control, select "Pair speed sensor", and then click the icon of the speed sensor with the same name).

**Comment by EvanMulawski** [comment]
There will inevitably be some RGB lag/stutter as two programs need to share control of the device (especially at higher animation speeds/framerate), but I may be able to make some improvements to lessen the impact.

**Comment by EvanMulawski** [comment]
New build [available](https://github.com/EvanMulawski/FanControl.CorsairLink/issues/111#issuecomment-1826597906).

Please re-test with SignalRGB - should be a *little* better with respect to RGB stutter.

**Comment by a-zndr** [comment]
> New build [available](https://github.com/EvanMulawski/FanControl.CorsairLink/issues/111#issuecomment-1826597906).
> 
> Please re-test with SignalRGB - should be a _little_ better with respect to RGB stutter.

Significantly better

**Comment by EvanMulawski** [comment]
Added in [v1.5.0-beta.1](https://github.com/EvanMulawski/FanControl.CorsairLink/releases/tag/v1.5.0-beta.1). Thanks, everyone!

**Comment by nicksmith26262626** [comment]
@EvanMulawski Im also not getting any lag in SignalRGB.  Thanks again!!!

**Comment by jhiggins** [comment]
This is looking pretty good on my system as well.  Thanks @EvanMulawski
