### ISSUE TITLE
Corsair Hydro Series H150i Pro RGB support?

### ISSUE THREAD

**Issue by Err0r0815** [EvanMulawski/FanControl.CorsairLink#114]
Hi,

ich have the Corsair Hydro Series H150i Pro RGB and im clear that this product dont listed on the "support page".
its a bit older piece of hardware but works still fine.

ist it possible to add support, that i can manage it in fancontrol? 
would be nice :).

greetings

**Comment by EvanMulawski** [comment]
@Err0r0815 Can you provide the hardware ID of the device using Device Manager or [USBDeview](https://www.nirsoft.net/utils/usbdeview-x64.zip)?

**Comment by EvanMulawski** [comment]
@Err0r0815 That device is supported. Let me know if you have any issues.

**Comment by EvanMulawski** [comment]
Can you provide the CorsairLink.log file and a screenshot of Fan Control?

**Comment by Err0r0815** [comment]
yes

[CorsairLink.log](https://github.com/EvanMulawski/FanControl.CorsairLink/files/13210221/CorsairLink.log)
![image](https://github.com/EvanMulawski/FanControl.CorsairLink/assets/35954165/5b2a75f1-f694-456c-8d99-02d28557ce0b)

**Comment by EvanMulawski** [comment]
Ah, you need to install a driver:

https://github.com/EvanMulawski/FanControl.CorsairLink#siusbxpress-driver

**Comment by Err0r0815** [comment]
Ah thanks man!!
i forgot to copy the 2nd dll into the plugin folder :)

thanks!! now its working :)
