### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by BrendanMan3** [EvanMulawski/FanControl.CorsairLink#117]
[log.txt](https://github.com/EvanMulawski/FanControl.CorsairLink/files/13200526/log.txt)
[CorsairLink.log](https://github.com/EvanMulawski/FanControl.CorsairLink/files/13200528/CorsairLink.log)
Please see the attached logs. Thank you.

**Comment by BrendanMan3** [comment]
Where in device manager would it show?

**Comment by EvanMulawski** [comment]
It should appear under Human Interface Devices, but it may be easier to use [USBDeview](https://www.nirsoft.net/utils/usbdeview-x64.zip).

**Comment by BrendanMan3** [comment]
Ok tried a fresh update to fan control and in settings the plugins say no plugins loaded?

**Comment by BrendanMan3** [comment]
[CorsairLink.log](https://github.com/EvanMulawski/FanControl.CorsairLink/files/13629779/CorsairLink.log)
Heres the log
