### ISSUE TITLE
Corsair H110i GT does not return to a good default state after exiting Fan Control

### ISSUE THREAD

**Issue by Nebur99** [EvanMulawski/FanControl.CorsairLink#118]
After having used Fan Control. the next time the AIO is powered up, it will be  in a dangerous state, as follows:
- pump running at very low ~200rpm (no typo, measured directly on pumps 'fan output' via one of the motherboard's fan ports, confirmed with a mechanics stethoscope - the rotor is not even running and trying to start up again and again...)

- fans running at minimum speed with no regard for current liquid temp

I noticed this after rebooting and entering the bios and then noticing that the cpu was unreasonably hot. Observations show that it happens whenever Fan Control has been running, was stopped and the AIO's power is cycled (e.g. system shutdown, reboot, sleep).

Only way to zapp the AIO back to a usable state, is starting Fan Control or Corsair LINK 4 again.

Another observation with no immediate meltdown consequences : 
- when Fan Control is started the AIO's pump and fan speeds are casually reduced for no good reason
- this is in a 'virgin state' with just installing/enabling the plugin - no curves, manual mode and 'slider button' on the pump control off
- log shows:
      _Requested power for channel 0: 50 %
      Requested power for channel 1: 50 %
      Requested power for channel 2: 50 %_
- why would that seem to be a good decision? If anything the pump and fan speed should be left unaltered till the user requests changes or alternatively - if technically not possible to act passively - ramped up to 100% to be sure to cause no harm.

The attached log contains a few minutes run of Fan Control from start to end of the process. There is really nothing sticking out, specially at the end, when Fan Control was closed.

**Thanks in advance for looking into this!**

[CorsairLink.log](https://github.com/EvanMulawski/FanControl.CorsairLink/files/13232114/CorsairLink.log)

**Comment by EvanMulawski** [comment]
> After having used Fan Control. the next time the AIO is powered up, it will be in a dangerous state, as follows:
> 
> - pump running at very low ~200rpm (no typo, measured directly on pumps 'fan output' via one of the motherboard's fan ports, confirmed with a mechanics stethoscope - the rotor is not even running and trying to start up again and again...)
> 
> - fans running at minimum speed with no regard for current liquid temp
> 
> I noticed this after rebooting and entering the bios and then noticing that the cpu was unreasonably hot. Observations show that it happens whenever Fan Control has been running, was stopped and the AIO's power is cycled (e.g. system shutdown, reboot, sleep).
>
> Only way to zapp the AIO back to a usable state, is starting Fan Control or Corsair LINK 4 again.

That is odd - it should revert to its default hardware profile when it's not being controlled by software. The only thing I would be able to do is explicitly set the modes to "Default" when exiting Fan Control (cleanly), but I'm not sure that would solve the issue.

If you shut down the PC, disconnect the AIO from the motherboard fan header, and power on the PC, does the AIO operate differently?

---

> Another observation with no immediate meltdown consequences : 
> - when Fan Control is started the AIO's pump and fan speeds are casually reduced for no good reason
> - this is in a 'virgin state' with just installing/enabling the plugin - no curves, manual mode and 'slider button' on the pump control off
> - log shows:
>       _Requested power for channel 0: 50 %
>       Requested power for channel 1: 50 %
>       Requested power for channel 2: 50 %_
> - why would that seem to be a good decision? If anything the pump and fan speed should be left unaltered till the user requests changes or alternatively - if technically not possible to act passively - ramped up to 100% to be sure to cause no harm.

This is tricky - I just chose 50% on a whim when initially developing the plugin because it was a value that worked for me, but I can see how others would prefer 100% as the default. However, a counterpoint to that is this: you are using Fan Control - why wouldn't you want to enable/control all of your cooling devices (and, by extension, not use the defaults)?

I will log this as a future enhancement.

**Comment by Nebur99** [comment]
> That is odd - it should revert to its default hardware profile when it's not being controlled by software. The only thing I would be able to do is explicitly set the modes to "Default" when exiting Fan Control (cleanly), but I'm not sure that would solve the issue.
> 
> If you shut down the PC, disconnect the AIO from the motherboard fan header, and power on the PC, does the AIO operate differently?


Nope - the AIO stays in the crippled state even after disconnecting everything and trying several times to get it running. It's as if the ROM saves a corrupted profile that prevents it from running and is cleared out by reconnecting with the original LINK software. I agree that betting on a graceful shutdown to revert things to default is no solution. 
Are you 'forcing' the manual control somehow by trickery? The LINK software appears to just upload a configured profile and the fan curves are then followed by the firmware. There is no 'live' control.

 
> This is tricky - I just chose 50% on a whim when initially developing the plugin because it was a value that worked for me, but I can see how others would prefer 100% as the default. However, a counterpoint to that is this: you are using Fan Control - why wouldn't you want to enable/control all of your cooling devices (and, by extension, not use the defaults)?


Well, the thing is that I wouldn't expect that just installing the plugin will actively change the device settings. All other fans that are controlled by Fan Control w/o plugin, are unaffected till I decide to override the firmware control and toggle the corresponding switch. I think 100 is better than 50% - at least you hear the fans ramping up and know things have changed on their own.
Also active control of the AIO is not necessarily the original intention. E.g. in my case I just wanted to have the AIO fan speeds as sensors to sync some intake fans to them with an offset to ensure positive case pressure.


> I will log this as a future enhancement.

Cool! And thanks for the super fast response!

**Comment by EvanMulawski** [comment]
> Are you 'forcing' the manual control somehow by trickery? The LINK software appears to just upload a configured profile and the fan curves are then followed by the firmware. There is no 'live' control.

Have you tried iCUE 4? I'm sending the same commands as iCUE and it allows controlling the device "live." Also, there might be a firmware update for the device and you can check/install using iCUE.

**Comment by Nebur99** [comment]
I wasn't aware of iCUE being compatible with this very old device. Installed it and did some tests:
- indeed the fans are controlled via software when a sensor other than the internal temp sensor is used
- the same is true for LINK, I just didn't notice that other sensors were selectable

I enabled this software mode and shut down the computer hard and ungracefully (long press power button) to see what happens with the AIO when no potential 'disconnect' command is sent from iCUE or LINK
- the AIO came up fine and functional with no issues

So there must be something that the corsair software does when taking over control that your plugin does not. It imagine there might be some initialization command before entering external control mode that the firmware considers on the next start.

I'm not too invested in finding a solution (HWINFO plugin covers my reqs to read aio fan rpms for sync) but if you are willing to investigate the issue, let me know if I can help by taking an usb trace or something. That's assuming you won't have the exact same aio at hand...

**Comment by EvanMulawski** [comment]
Would you be able to follow https://github.com/EvanMulawski/FanControl.CorsairLink/discussions/86#discussioncomment-6887650 to provide a USB capture during operation with iCUE and/or LINK?

**Comment by Nebur99** [comment]
> Would you be able to follow [#86 (reply in thread)](https://github.com/EvanMulawski/FanControl.CorsairLink/discussions/86#discussioncomment-6887650) to provide a USB capture during operation with iCUE and/or LINK?

Sure. I actually develop wireshark dissectors, so its all on board. But it will take a few days because the machine is disassembled right now waiting for a new case to get delivered.

**Comment by EvanMulawski** [comment]
@Nebur99 Would you be able to provide the USB capture?

**Comment by Nebur99** [comment]
> @Nebur99 Would you be able to provide the USB capture?

Thanks for the reminder. I will. Life - other priorities popped up. The days between the holidays will hopefully offer some 'hobby time'...
