### ISSUE TITLE
Commander Core ELITE CAPELLIX: The expected data type was not read within the specified time.

### ISSUE THREAD

**Issue by Tcris1000** [EvanMulawski/FanControl.CorsairLink#121]
I haven't gotten this plugin to work, every time I launch it it gives me this error.
I am using a Corsair H100i Elite LCD with the included Capellix Commander Pro, I just double checked all the wiring everywhere and there are no issues on that. The devices are showing up in device manager. I have tried installing the driver included in the .zip file in case that did anything but it did not.
I am using v173 FanControl 4_8 and V1.4.1 CorsairLink.

The message in the log says Operation canceled: The expected data type was not read within the specified time.
Help would be appreciated

Logs:
[CorsairLink.log](https://github.com/EvanMulawski/FanControl.CorsairLink/files/13314038/CorsairLink.log)
[log.txt](https://github.com/EvanMulawski/FanControl.CorsairLink/files/13314040/log.txt)

**Comment by EvanMulawski** [comment]
Hi @Tcris1000, please try the build linked in https://github.com/EvanMulawski/FanControl.CorsairLink/issues/112#issuecomment-1763497697. Let me know if that works and post the CorsairLink.log file after testing.

**Comment by Tcris1000** [comment]
It still didn't work, I think it gave a different error though

[CorsairLink.log](https://github.com/EvanMulawski/FanControl.CorsairLink/files/13314941/CorsairLink.log)

**Comment by EvanMulawski** [comment]
@Tcris1000 Do you have any other software running that would be communicating with the device? e.g. OpenRGB, SignalRGB, iCUE, etc.

**Comment by Tcris1000** [comment]
I just tried it again right now with the other build and it worked this time. As far as I know nothing changed, it just worked this time. I think previously I might have accidentally still been using the normal, most recent build. But it is working currently with the build from #112. Thanks for the help!

**Comment by EvanMulawski** [comment]
Fixed in v1.4.2
