### ISSUE TITLE
Corsair AX1200i can't bypass min fan speed

### ISSUE THREAD

**Issue by lordtyrion2005** [EvanMulawski/FanControl.CorsairLink#126]
iCue and Link4 have a minimum fan speed of 40% when using curves or fixed speed. I'd hoped FanControl could bypass this minimum and allow me to set it to a more comfortable (quieter) 15-20%. Unfortunately when a speed below 40% is selected the PSU will switch to zeroRPM mode.

Any suggestions most welcome :-)

**Comment by EvanMulawski** [comment]
Hi @lordtyrion2005, this plugin should allow the AXi PSU series fan to be set to 15%. Can you confirm the model is AX1200i and not HX1200i?

From the Device Support matrix footnotes:

> 6. When the fan power is set to 0%, control of the fan will be returned to the PSU allowing zero-RPM operation. When the fan power is set to 1% or higher, control of the fan will be returned to Fan Control. The minimum duty depends on the model:
> 
>    | PSU Model | Min. Duty |
>    | --------- | --------- |
>    | HXi/RMi   | 30%       |
>    | AXi       | 15%       | 

The minimum duties are in place because the fan will not spin below its minimum operating RPM; i.e. you could set it to 5% but it would not be spinning.

**Comment by lordtyrion2005** [comment]
Hi @EvanMulawski ,
Really appreciate the response.
It's an AX1200i. When setting a fixed speed below 40% - the fan will still spin at 700/720RPM (40%). If you set a speed below 25% the fan will spin down (over about 10-15 seconds) to 0 RPM. 

Because of the lag in going to 0 RPM. Fan stop detection see's a fan spinning until 3% however from 40% down the fan is still at 700/720 RPM and will eventually go to 0.

I've had some success editing iCue config files unfortunately its not stable and doesn't last through restart. I was able to get a hacked Corsair Link4 .dll for an Ax1600i - which allows you to set below 40% however fan will still run at 40%.

I'm wondering if there's a hard minimum limit on the drivers themselves. Will edit the assemblies tomorrow and have a look.

N.B. The AX1200i is not implicitly listed in the driver .inf file - it has the 1500 and 1600. I have no idea if that's an issue.

**Comment by EvanMulawski** [comment]
It looks like a different model of fan is used in the AX1200i (vs the AX1600i I have), a Yate Loon D14BH-12 ([source](https://www.techpowerup.com/review/corsair-ax1200i/5.html)). Not sure what the rated minimum operating RPM of that fan is. The fan itself is what determines the minimum RPM it can run at, as the driver does not know anything about the device at this level. There are also manufacturing tolerances, so one D14BH-12 could have a minimum operating RPM of 700 and another D14BH-12 could have a minimum operating RPM of 600, for example.

The AX1200i model is covered under the "CorsairLink USB Dongle" device (`1c00`) which includes several other AXi PSU models.

It is technically possible to replace the fan in the PSU with one that is quieter and/or supports ultra-low RPM operation (e.g. Noctua).
