### ISSUE TITLE
CorsairLink could not initialize or has no sensors 

### ISSUE THREAD

**Issue by BrendanMan3** [EvanMulawski/FanControl.CorsairLink#130]
Logs attached 
[CorsairLink.log](https://github.com/EvanMulawski/FanControl.CorsairLink/files/13757356/CorsairLink.log)
[log.txt](https://github.com/EvanMulawski/FanControl.CorsairLink/files/13757357/log.txt)

**Comment by EvanMulawski** [comment]
See #127 and #80.

**Comment by BrendanMan3** [comment]
I saw them but I don't see any solutions. Is the H115i Platinum RGB not compatible? What am I missing? Do I need to have Corsair iCUE installed but not running?

**Comment by EvanMulawski** [comment]
@BrendanMan3 You would need to either reboot the PC or start iCUE and wait for it to reboot the device. I'm working on a solution and will notify those experiencing this issue in #80 - likely today or tomorrow.
