### ISSUE TITLE
FanControl Stops Commander Core XT hardware RGB

### ISSUE THREAD

**Issue by staretoolong55** [EvanMulawski/FanControl.CorsairLink#131]
Fan Control 175 and plugin 1.4.3
Also using FanControl.LianLiPlugin.dll 

I am not using Corsair fans, and I am just controlling the pump using the MB header via Fan Control.    I am using LianLi Unifans.  Most of my water cooling is Corsair Hydro X.   I typically have ICUE fully closed.  

I had everything working off CPU and GPU temps, but I could not get my water temp sensor on my Asus motherboard to read in.   I tried your plugin to read the water temp from Corsair Commander Core XT .   The temp read in and worked great, so I thought I was set, but then I noticed it was stopping the Corsair RGB.    All the lighting is through the Commander Core XT (holding a dim static color on Hydro X GPU block, pump/res, and CPU Block).   

If I close Fan Control, the lights work with ICUE open.  They work with ICUE fully closed including the taskbar service.    As soon as I reopen Fan Control, it kills the RGB on the corsair products.   Lights on MB and Lian Li fans all keep working.    Close Fan control, then open ICUE...rinse and repeat.  

[CorsairLink.log](https://github.com/EvanMulawski/FanControl.CorsairLink/files/13758357/CorsairLink.log)

**Comment by EvanMulawski** [comment]
Hi @staretoolong55, in order to read from and control the Commander CORE XT, it needs to be in software mode, which will also change lighting from hardware mode to software mode. You will need to use SignalRGB to control lighting when Fan Control is running.

**Comment by staretoolong55** [comment]
I understand.  That works.  

Thank you.
