### ISSUE TITLE
Failing to load plugin

### ISSUE THREAD

**Issue by ligistx** [EvanMulawski/FanControl.CorsairLink#137]
Corsair iCue is not running and getting the below error on loading of Fan Control. Tried to drop and instal the driver into the plugsins folder as well, that didn't seem to help. Persists across PC reboots.

I have a Commander Pro.

![image](https://github.com/EvanMulawski/FanControl.CorsairLink/assets/44333637/7dc7bae7-0373-48b8-9cb2-0fbe0ae3a143)

**Comment by EvanMulawski** [comment]
Hi @ligistx, please make sure you followed the [installation instructions](https://github.com/EvanMulawski/FanControl.CorsairLink?tab=readme-ov-file#installation) and post the `log.txt` file located in the Fan Control directory.
