### ISSUE TITLE
Commander Core flickering with SignalRGB

### ISSUE THREAD

**Issue by TonyXVN** [EvanMulawski/FanControl.CorsairLink#138]
After I updated to version 1.51. It sill has stutter/flickering on rgb effect when when using SignalRGB.

**Comment by EvanMulawski** [comment]
Hi @TonyXVN, what device(s) are stuttering and what version of SignalRGB are you using?

**Comment by TonyXVN** [comment]
Hi, @EvanMulawski.
Thank you for your response. I'm sorry, didn't mention in previous post. I'm using Corsair Commander Core and SignalRGB 2.3.43 at the moment.

**Comment by PinkLasagna03** [comment]
> Hi, @EvanMulawski. Thank you for your response. I'm sorry, didn't mention in previous post. My PC has few RGB devices, but just only RGB fan control by Corsair Commander Core is stuttering. I'm using SignalRGB 2.3.43 at the moment.

I have the same issue. When deleting the plugin it doesn't flicker, but when using it, it starts flickering again. I also use Corsair Commander Core with SignalRGB 2.3.43. For some reason it flickers to a weird blue/pink color instead of keeping the effect.

**Comment by EvanMulawski** [comment]
@TonyXVN @PinkLasagna03 Please try the attached build.

[FanControl.CorsairLink-CCIssue-v20240327r001.zip](https://github.com/EvanMulawski/FanControl.CorsairLink/files/14781504/FanControl.CorsairLink-CCIssue-v20240327r001.zip)

**Comment by EvanMulawski** [comment]
Closing as stale - likely resolved in v1.6.0-beta.4 and later versions.
