### ISSUE TITLE
Support for XC7 Elite

### ISSUE THREAD

**Issue by berkona** [EvanMulawski/FanControl.CorsairLink#139]
I recently added an XC7 Elite to my system.  This uses the link system for both addressable RGB lights as well as a temperature sensor for the cold plate.  I would like to be able to control the RGB lights via Signal RGB and get the temp sensor to show up in Fan Control.  

How would I go about doing the USB captures required to get support for this?

I'd be happy to beta-test any changes you have for this after providing the capture and I can also maybe contribute some code if you point me to the docs for adding a new link component.

**Comment by EvanMulawski** [comment]
Hi @berkona, I just added USB packet capture [instructions](https://github.com/EvanMulawski/FanControl.CorsairLink/wiki/USB-Packet-Capture) to the wiki. Let me know if you need any assistance. Thanks!

**Comment by EvanMulawski** [comment]
@berkona Just checking if you will be able to provide a packet capture using the instructions above. Thanks!

**Comment by berkona** [comment]
@EvanMulawski sorry for the delay.  I was caught up in some other things.  Attached is the pcap that I _believe_ is captured correctly: [xc7-elite.zip](https://github.com/EvanMulawski/FanControl.CorsairLink/files/14230471/xc7-elite.zip)

0-10 seconds is idle, then iCue was started around 10 seconds and left without any input until 70 seconds.  
Post 70 seconds I changed some of the light-related settings.  
First set all LEDs to white then to random other colors then set a few individual LEDS to a color then two non-contiguous strips to the same color.  Hopefully this is enough to work with.  

Let me know if I need to capture different settings or anything else to do with the capture.

System consists of a single iCue Link hub with 3 120mm QX fans in linked in series to the port on one side.  The port on the other side is connected directly to the XC7 Elite

**Comment by EvanMulawski** [comment]
@berkona Thanks! Do you have the Stealth Gray or White color XC7?

@Heal-Bot Packet capture for iCUE LINK XC7 RGB ELITE. Device type is `0x09`.

**Comment by berkona** [comment]
It’s the stealth gray oneSent from my iPhoneOn Feb 10, 2024, at 17:23, Evan Mulawski ***@***.***> wrote:﻿
@berkona Thanks! Do you have the Stealth Gray or White color XC7?
@Heal-Bot Packet capture for iCUE LINK XC7 RGB ELITE. Device type is 0x09.

**Comment by EvanMulawski** [comment]
@berkona Please try the attached build (follow the typical installation process). You should see the XC7's temperature sensor.

[FanControl.CorsairLink-LinkXc7Support-v20240210r001.zip](https://github.com/EvanMulawski/FanControl.CorsairLink/files/14230751/FanControl.CorsairLink-LinkXc7Support-v20240210r001.zip)

**Comment by berkona** [comment]
Yep I can now see the temp sensor.  Thanks!

**Comment by EvanMulawski** [comment]
Completed in v1.6.0-beta.2
