### ISSUE TITLE
Pump control (quiet mode) stops working intermittenly (H150i Pro)

### ISSUE THREAD

**Issue by Arnagos** [EvanMulawski/FanControl.CorsairLink#141]
The control for the pump speed sometimes just stops working.

Setting the pump speed to any value in the range of 0-33%, which should set it to quiet mode, doesn't change the actual mode.
It sometimes works, and sometimes doesn't. It feels like the firmware is overwriting the mode under certain cirumstances.

![image](https://github.com/EvanMulawski/FanControl.CorsairLink/assets/21961872/f3499a80-483d-474c-9c48-7c27885f5c72)

Increasing the value to 100% on the other hand _does_ change the mode.

![image](https://github.com/EvanMulawski/FanControl.CorsairLink/assets/21961872/8e160791-de32-4141-ba48-95bb79b84446)

Fan Control: V179
Plugin: V1.5.1
Hardware: H150i Pro
OS: Windows 11 22H2

**Comment by EvanMulawski** [comment]
Hi @Arnagos, can you post your CorsairLink.log file (located in the same directory as Fan Control). Also, please post the value of the liquid temperature sensor for the device - both when it is functioning as expected and when it is not. Thanks!
