### ISSUE TITLE
Open fan controll before ICUE

### ISSUE THREAD

**Issue by craftercis** [EvanMulawski/FanControl.CorsairLink#148]
Hello,

It is not totally clear for me if I have to uninstall ICUE completely if I want to use this tool? The description says this:

_"This plugin will not function correctly if Corsair iCUE and the "Corsair Service" service is running. These programs should be stopped **before** running Fan Control."_

Does that mean I can use ICUE normally (mainly for my Nexus and AIO screen) if I start it AFTER FanControl is started?

**Comment by EvanMulawski** [comment]
Hi @craftercis, iCUE cannot be running at all if this plugin is used with Fan Control. To use software-based RGB you will need to use SignalRGB or OpenRGB alongside Fan Control.

**Comment by craftercis** [comment]
> Hi @craftercis, iCUE cannot be running at all if this plugin is used with Fan Control. To use software-based RGB you will need to use SignalRGB or OpenRGB alongside Fan Control.

Thanks for the fast answer! Then I have only one more question. My nvidia card goes to 30% after it hits some fixed temp. I enabled the force set option in the FanControl app but that doesn't set it to 0 with my custom graph. Only when I do CTRL+R it will be 0% again. Afterburner is fully deleted. Is there a way to fix this that you know?

**Comment by EvanMulawski** [comment]
> Thanks for the fast answer! Then I have only one more question. My nvidia card goes to 30% after it hits some fixed temp. I enabled the force set option in the FanControl app but that doesn't set it to 0 with my custom graph. Only when I do CTRL+R it will be 0% again. Afterburner is fully deleted. Is there a way to fix this that you know?

See https://github.com/Rem0o/FanControl.Releases/wiki/Nvidia-30%25-and-0-RPM
