### ISSUE TITLE
Multiple errors detected FanControl error message - Message: Operation failed early: The device is not connected     Source: HidSharp

### ISSUE THREAD

**Issue by GuiLL31** [EvanMulawski/FanControl.CorsairLink#152]
hello,

I've got a H150 RGB Elite, running with fancontrol for several weeks now without issue.
recently got those errors message several times in a row.

happening idle and on load 

See enclosed pop error message & log file
![fancontrol error](https://github.com/EvanMulawski/FanControl.CorsairLink/assets/159967774/0fb4ca72-a8db-4a5e-a4cb-a53859f2a8f9)

[CorsairLink.log](https://github.com/EvanMulawski/FanControl.CorsairLink/files/14273318/CorsairLink.log)

**Comment by EvanMulawski** [comment]
Hi @GuiLL31, this is a common issue with the Hydro Platinum devices (see #80). A workaround is being implemented in v1.6 where the plugin will reboot the device after three consecutive failures. Please try [the latest v1.6 beta release](https://github.com/EvanMulawski/FanControl.CorsairLink/releases).

**Comment by GuiLL31** [comment]
many thanks. I'll test that. Isn't causing any damage to reboot the device like this?

**Comment by EvanMulawski** [comment]
> many thanks. I'll test that. Isn't causing any damage to reboot the device like this?

No - Corsair iCUE does the same thing.

**Comment by EvanMulawski** [comment]
Closing (see #80 and #144)
