### ISSUE TITLE
Corsair Fans/Sensors don't initialise/connect to fan control consistently 

### ISSUE THREAD

**Issue by Andyden4483** [EvanMulawski/FanControl.CorsairLink#153]
Hi - likely to be an issue with my setup but I hope you can help me diagnose.

I have a corsair H150i Pro. I still have Icue installed but I installed the drivers as per instructions 
![image](https://github.com/EvanMulawski/FanControl.CorsairLink/assets/157853140/83ef9146-af4c-4fd9-a067-c4a771b58562)

I have fan control set to start-up 5 minutes after boot as I hoped this would stop issues but it hasn't. I have Icue Still installed for the lighting - is this the problem?

On start-up I get failures with the corsair sensors but if I restart; 9 times out of 10 they kick in/are found nut ideally I'd like this to go away because Fan Control with the corsair link is one of the best fan controls I've ever used and love having everything in one place, so thanks for the work you've done/continue to do. I've added my logs to this post in case you can see any issues that are obvious - i'll get a screenshot the next time it happens if it helps but ive also added a DXDIAG export.

[CorsairLink.log](https://github.com/EvanMulawski/FanControl.CorsairLink/files/14318722/CorsairLink.log)
[DxDiag.txt](https://github.com/EvanMulawski/FanControl.CorsairLink/files/14318723/DxDiag.txt)

**Comment by EvanMulawski** [comment]
Hi @Andyden4483, iCUE (and the Corsair Service) cannot be running at all if this plugin is used with Fan Control. To use software-based RGB you will need to use SignalRGB or OpenRGB alongside Fan Control.

**Comment by Andyden4483** [comment]
SignalRGB doesnt find the pump LED - so thats "great"
