### ISSUE TITLE
iCUE LINK RX Fan support

### ISSUE THREAD

**Issue by Host-255** [EvanMulawski/FanControl.CorsairLink#156]
RX140 fan support required via Corsair Link.

**Comment by EvanMulawski** [comment]
Hi @Host-255, can you post your CorsairLink.log file (will be in the same directory as the Fan Control app)? Thanks.

**Comment by Host-255** [comment]
Hi Evan, 

Thanks for the response. Corsairlink.log attached. 
[CorsairLink.log](https://github.com/EvanMulawski/FanControl.CorsairLink/files/14747464/CorsairLink.log)

**Comment by EvanMulawski** [comment]
@Host-255 Please try [v1.6.0-beta.3](https://github.com/EvanMulawski/FanControl.CorsairLink/releases/tag/v1.6.0-beta.3). Also, do you have the RGB or non-RGB RX fans?

**Comment by Host-255** [comment]
Thanks Evan will do. I have both the RGB and non-RGB. For any avoidance of doubt, the RGB works perfectly fine.

**Comment by EvanMulawski** [comment]
@Host-255 Are your RX fans operational with that version? Just want to make sure. Thanks!

**Comment by Host-255** [comment]
HI @EvanMulawski sorry for the delay. RX fans are operational with your current version. Thanks!

**Comment by BizzWareX** [comment]
hey,

my RX Fans (4 pc) 120 (RGB) dont work, too

log says: unsupported iCUE Link device

[CorsairLink.log](https://github.com/EvanMulawski/FanControl.CorsairLink/files/14893410/CorsairLink.log)
