### ISSUE TITLE
XC7 RGB ELITE LCD support

### ISSUE THREAD

**Issue by Corkscrewme** [EvanMulawski/FanControl.CorsairLink#158]
I saw you had added the XD7 elite and wondering if you could add the LCD version as well?

**Comment by Corkscrewme** [comment]
I'm not sure if I got the cap right so if I need to do it again please let me know.
[XD7 Elite LCD usbcap.zip](https://github.com/EvanMulawski/FanControl.CorsairLink/files/14782584/XD7.Elite.LCD.usbcap.zip)

**Comment by EvanMulawski** [comment]
This model does not communicate through iCUE LINK as it connects directly to the host via USB. I'll have to take a look at the protocol.

**Comment by EvanMulawski** [comment]
@Corkscrewme Please try the attached build.

[FanControl.CorsairLink-Xc7LcdSupport-v20240414r001.zip](https://github.com/EvanMulawski/FanControl.CorsairLink/files/14973545/FanControl.CorsairLink-Xc7LcdSupport-v20240414r001.zip)

**Comment by Corkscrewme** [comment]
@EvanMulawski  
Sorry for taking so long to respond.
[CorsairLink.log](https://github.com/EvanMulawski/FanControl.CorsairLink/files/15049229/CorsairLink.log)
I saw the sensor in the drop down list but it is only showing 0.1c for the temp.

**Comment by EvanMulawski** [comment]
@Corkscrewme Can you attach the newest log file? After a certain size, new log files are generated - should be `CorsairLink.N.log` where `N` is a number - look for the highest number. Thanks!

**Comment by Corkscrewme** [comment]
@EvanMulawski  Okay no problem.
[CorsairLink.1.log](https://github.com/EvanMulawski/FanControl.CorsairLink/files/15049486/CorsairLink.1.log)

**Comment by EvanMulawski** [comment]
@Corkscrewme New build.

[FanControl.CorsairLink-Xc7LcdSupport-v20240422r001.zip](https://github.com/EvanMulawski/FanControl.CorsairLink/files/15069253/FanControl.CorsairLink-Xc7LcdSupport-v20240422r001.zip)

**Comment by Corkscrewme** [comment]
@EvanMulawski  Everything is working perfectly now. Thank you.

**Comment by EvanMulawski** [comment]
@Corkscrewme Officially released in [v1.6.0-beta.7](https://github.com/EvanMulawski/FanControl.CorsairLink/releases/tag/v1.6.0-beta.7)
