### ISSUE TITLE
H115i Pro RGB Elite not detected

### ISSUE THREAD

**Issue by No-good-deed-goes-unpunished** [EvanMulawski/FanControl.CorsairLink#160]
CW-9060059-WW
Tried plugging USB cable into both Motherboard USB headers
Tried all versions of corsairlink.dll from v1.4.3 up to and including 1.6.0 beta versions.
Is this cooler supported?

Motherbaord: MSI X299 XPower Gaming AC, I9-10940X CPU.

**Comment by EvanMulawski** [comment]
Hi @No-good-deed-goes-unpunished, from your log file in #161 it appears to be detected and the sensors/controllers are populated. Are you still having a problem with this device?

**Comment by No-good-deed-goes-unpunished** [comment]
Yes. every time I boot up the PC it pops up and error saying no devices or sensors were detected. I'll go and reboot it now and then attach the popup.

But this does beg the question: How can fan control remember devices when I completely remove the entire folder (I'm using the portable version). Were it not for the fact that it somehow remembers what was detected from some point in history there would be no sensors shown. As you would have seen from the log file, on this PC its installed on D:\Fan Control.

**Comment by No-good-deed-goes-unpunished** [comment]
As a test to verify the cooler is not faulty I installed Corsairlink 4.9.9.3 (The actual "Corasir" product). I figured if that software doesn't detect the cooler either then it must be faulty.

Corsairlink detects the cooler without issue. Though it has some limitations compared to Fan Control.

This product won't work on recent motherboards, but the two PCs I'm having issues with are both X299 motherboards.

**Comment by EvanMulawski** [comment]
Can you post a debug log for this one as well?

**Comment by No-good-deed-goes-unpunished** [comment]
I purchased and installed the CW-9060059-WW cooler.
However, according to the Corsairlink Plugn this is an old Hydro device. That means is requires siUSBxp.sys- The H115i Pro, 

This is what's in the PC;
https://www.corsair.com/us/en/p/cpu-coolers/cw-9060059-ww/icue-h115i-rgb-elite-liquid-cpu-cooler-cw-9060059-WW

The dll you provide with the plugin won't install if the siUSBxp.sys file does not already exist in c:\windows\System32\Drivers.
I had to install Corsairlink, then uninstall it (The siUSBxp.sys file is installed as a separate package).The file is dated 2018 from the installer I used (4.9.9.3). 

Anyway, it doesn't matter to me what it detects is as, provided it detects it because my pc was being cooked when I was running without CPU cooling.

I don't have the time to pull the PC apart and check the label. The fans are black and the pump has the rounded RGB corners, where as the CW-9060044-WW has white fans and a angled RGB shape on the corners - so it looks like the CW-9060059-WW

**Comment by EvanMulawski** [comment]
> The dll you provide with the plugin won't install if the siUSBxp.sys file does not already exist in c:\windows\System32\Drivers.
> I had to install Corsairlink, then uninstall it (The siUSBxp.sys file is installed as a separate package).The file is dated 2018 from the installer I used (4.9.9.3).

The .sys files will be installed if you install the driver package included in the release downloads (https://github.com/EvanMulawski/FanControl.CorsairLink?tab=readme-ov-file#siusbxpress-driver).

**Comment by EvanMulawski** [comment]
Would you be able to provide USB packet captures for this as well? (Same as #161, once with Fan Control and once with Corsair's software.)
