### ISSUE TITLE
iCUE LINK RX RGB Fan support

### ISSUE THREAD

**Issue by BizzWareX** [EvanMulawski/FanControl.CorsairLink#162]
hey,

my RX Fans 120 (RGB) dont work, too
have 4 of them installed
log says: unsupported iCUE Link device

[CorsairLink.log](https://github.com/EvanMulawski/FanControl.CorsairLink/files/14893410/CorsairLink.log)

_Originally posted by @BizzWareX in https://github.com/EvanMulawski/FanControl.CorsairLink/issues/156#issuecomment-2041061560_

**Comment by BizzWareX** [comment]
ah sorry my fault, cant edit the title

**Comment by EvanMulawski** [comment]
Added in [v1.6.0-beta.4](https://github.com/EvanMulawski/FanControl.CorsairLink/releases/tag/v1.6.0-beta.4)

**Comment by BizzWareX** [comment]
dont work

see log:
[CorsairLink.log](https://github.com/EvanMulawski/FanControl.CorsairLink/files/14913352/CorsairLink.log)

**Comment by EvanMulawski** [comment]
@BizzWareX Apologies - used the wrong type code. Fixed in [v1.6.0-beta.5](https://github.com/EvanMulawski/FanControl.CorsairLink/releases/tag/v1.6.0-beta.5).
