### ISSUE TITLE
instructions say to use the plugin dll and put it in the plugin folder, but no dll link???

### ISSUE THREAD

**Issue by keiraxlicious** [EvanMulawski/FanControl.CorsairLink#167]
im very confused w/ github. i dont see the normal box at the bottom w/ links to download. how do i download thendll for my corsair commander pro?

**Comment by EvanMulawski** [comment]
Hi @keiraxlicious, go to [Releases](https://github.com/EvanMulawski/FanControl.CorsairLink/releases), pick the one you want to use, expand **Assets**, and download the **FanControl.CorsairLink-VERSION.zip** file. This compressed folder will contain the DLL file.
