### ISSUE TITLE
Corsair Icue

### ISSUE THREAD

**Issue by recoverrelax** [EvanMulawski/FanControl.CorsairLink#173]
Hi. I have setup icue to hardware mode, which means it is not running but my commander core xt will control the lighting effect.
When i open the FanControl with this plugin, the lights gets disabled. How can i fix this.

**Comment by EvanMulawski** [comment]
Hi @recoverrelax, hardware lighting cannot be used when the device is in software mode, which is required to use this plugin. This is a limitation of the device itself and is noted in the [Device Support](https://github.com/EvanMulawski/FanControl.CorsairLink?tab=readme-ov-file#device-support) matrix (footnote 1). You will need to use software to control the lighting, e.g. SignalRGB or OpenRGB (see [Interoperability](https://github.com/EvanMulawski/FanControl.CorsairLink?tab=readme-ov-file#interoperability)).
