### ISSUE TITLE
Add support for Lighting Node CORE

### ISSUE THREAD

**Issue by ddulude95** [EvanMulawski/FanControl.CorsairLink#176]
Hi there, looking to add support for this product https://www.corsair.com/us/en/p/ambient-lights/cl-8930009/icue-lighting-node-core-digital-fan-rgb-lighting-controller-cl-8930009

I've attached a usb capture, and for quick filtering, use `usb.src == "1.7.0"` as I have already identified that to be the source of the corsair device.

Thank you for creating this plugin!

[lightningcorenode.zip](https://github.com/user-attachments/files/15894970/lightningcorenode.zip)

this might also be useful 
[CorsairLink.log](https://github.com/user-attachments/files/15895154/CorsairLink.log)

And this is the only text contained in the log.txt file:

6/18/2024 10:07:11 PM: CorsairLink could not initialize or has no sensors.
6/18/2024 10:18:43 PM: CorsairLink could not initialize or has no sensors.
6/18/2024 10:26:51 PM: CorsairLink could not initialize or has no sensors.
6/18/2024 10:31:59 PM: CorsairLink could not initialize or has no sensors.
6/18/2024 10:37:52 PM: CorsairLink could not initialize or has no sensors.
6/18/2024 10:44:34 PM: CorsairLink could not initialize or has no sensors.
6/18/2024 10:47:34 PM: CorsairLink could not initialize or has no sensors.
6/18/2024 11:46:55 PM: CorsairLink could not initialize or has no sensors.

**Comment by ddulude95** [comment]
Actually the more i research this device, i think it doesn't even control fan speeds at all. I installed this corsairlink plugin because on a no-plugin version of FanControl, manually setting fan speeds to 0 wasnt affecting my fans at all, so I couldn't identify them, leading me to think I needed this plugin. Now im rethinking everything lmao. I wonder if i daisy chained all my fans together and plugged them into a mobo header...ill have to check that

**Comment by EvanMulawski** [comment]
Hi @ddulude95, that is correct - the Lighting Node only controls RGB headers and not fan speeds.
