### ISSUE TITLE
RMi 750 jumps from 0 to current temp

### ISSUE THREAD

**Issue by aiac** [EvanMulawski/FanControl.CorsairLink#179]
HwInfo shows correct values, without jumping to zero. This plugin however causing FanSpeed to show 0 C from time to time (it happens every 1-2 second):
![corsair_rmi750](https://github.com/EvanMulawski/FanControl.CorsairLink/assets/8200156/b2db0486-443c-4833-b5f6-0e3f56cf0d7b)

**Comment by EvanMulawski** [comment]
Hi @aiac, can you [enable debug logging](https://github.com/EvanMulawski/FanControl.CorsairLink#configuration) and reproduce this? Please attach the CorsairLink.log file(s) to your reply. Thanks!
