### ISSUE TITLE
Corsair link could not initialize or has no sensors

### ISSUE THREAD

**Issue by Garnila** [EvanMulawski/FanControl.CorsairLink#186]
Hey guys I have an x570 tower with factory fans on the front and I want to control them via SignalRGB. When I try to install the plugin i get this message "Corsair link could not initialize or has no sensors". Is it something wrong with the wiring? Do I have to overlook corsair hub? 
![Screenshot 2024-08-22 041147](https://github.com/user-attachments/assets/99b783c3-a03f-424d-8ab1-5f4713e5b494)

**Comment by EvanMulawski** [comment]
Hi @Garnila, your fans are likely connected directly to the motherboard fan headers or via a basic splitter, so you don't need this plugin.
