### ISSUE TITLE
Color On Fans Changing

### ISSUE THREAD

**Issue by ghost** [EvanMulawski/FanControl.CorsairLink#187]
I have a Corsair h115i Platinum that I use with this software / plugin, when I was on windows 10 everything worked perfectly fine. Now I have upgraded to windows 11 because of the performance bump ryzen chips are getting and now Everytime this software gets loaded, it changes my fan colors to pure white instead of staying on cotton candy rainbow. It didn't do this on windows 10 so what could have changed?

**Comment by EvanMulawski** [comment]
Hi @DegenerateCoomer, I'm not sure why that would have changed after upgrading Windows, but the RGB resetting to white is expected as of v1.6.0. Users are expected to either use an RGB program (OpenRGB or SignalRGB) or configure a static color using environment variables.

**Comment by EvanMulawski** [comment]
v1.6.0 will automatically restart the AIO if it locks up, which is a common problem. However, the RGB needs to be reset when that happens. I am attempting to support the default RGB presets (see #170) but the primary focus of this plugin is cooling as there are other RGB solutions available.
