### ISSUE TITLE
Commander PRO not sensing speed?

### ISSUE THREAD

**Issue by cmdshft** [EvanMulawski/FanControl.CorsairLink#199]
I have a very weird setup admittedly, so bear with me. My system uses a Commander Pro for 2 temp probes and controlling an EK D5 pump (set in fan port 6), and I use a Lian Li fan controller (which is used by a different plugin). The CorsairLink plugin doesn't seem to be able to detect the reported speed of the pump in the C-Pro, and shows like this in the app:

![image](https://github.com/user-attachments/assets/f99165d2-93b0-4c18-a11f-9c082078d253)

How can I fix this so that it reports the speed and shows as calibrated?

**Comment by cmdshft** [comment]
Anything? Is this project abandoned?

**Comment by EvanMulawski** [comment]
Hi @cmdshft, you would just need to pair the speed sensor. Click "Pair speed sensor" for that control, select the correct speed sensor in the popup, then click OK. 

Then, to calibrate it automatically, select the control's menu (three dots next to the name) and select "Calibrate paired control automatically..."
