### ISSUE TITLE
Corsair Commander CORE Not Detected

### ISSUE THREAD

**Issue by Feath3rblade** [EvanMulawski/FanControl.CorsairLink#2]
First off, thank you so much for working on this plugin, I've been wanting a plugin that lets me move away from iCUE for a while and this looks like it'll probably be it. However, I just downloaded your latest release to test with my Commander CORE and whenever I launch FanControl I get the message: CorsairLink could not initialize or has no sensors. This message also shows up in the log.txt file, but with no further details.

I've already checked to make sure that all the Corsair and iCUE services on my PC are stopped, so that shouldn't be the issue. If you need any more information from me please feel free to ask, I really would like to see this work properly.

**Comment by EvanMulawski** [comment]
Hi @Feath3rblade,

Just to confirm, you also unblocked the file as noted in [Installation](https://github.com/EvanMulawski/FanControl.CorsairLink#installation)?

If that was not the cause, please download and run [USBDeview](https://www.nirsoft.net/utils/usbdeview-x64.zip). Look for your device, select the row, copy it (Ctrl-C will work), and paste it here.

**Comment by Feath3rblade** [comment]
`CORSAIR iCUE Commander CORE	USB Composite Device	Unknown	Yes	Yes	No	No		8206207076c8b0aa157470062091005f	2023-01-12 2:16:09 AM	2022-12-24 1:46:45 PM	1b1c	0c1c	1.00		00	00	00		FEATH3RBLADE-PC			6&1853d686&0	usbccgp	@usb.inf,%GenericParent.SvcDesc%;Microsoft USB Generic Parent Driver	usbccgp.sys		(Standard USB Host Controller)		100 mA	2.00	USB Composite Device	10.0.22621.608	Composite.Dev.NT	usb.inf	USB\VID_1B1C&PID_0C1C\8206207076c8b0aa157470062091005f	Removable, UniqueID, SurpriseRemovalOK					
`



I did unblock it, and double checked the dll after pasting it into the plugins folder

**Comment by Feath3rblade** [comment]
I also have 2 other devices with the same vendor id and product id as the commander core:
`0000.0014.0000.011.000.000.000.000.000	USB Input Device	HID (Human Interface Device)	Yes	Yes	No	No			2023-01-12 2:16:09 AM	2023-01-12 2:16:09 AM	1b1c	0c1c	1.00		03	00	00		FEATH3RBLADE-PC			7&2018b634&0	HidUsb	@input.inf,%HID.SvcDesc%;Microsoft HID Class Driver	hidusb.sys		(Standard system devices)				USB Input Device	10.0.22621.819	HID_Inst.NT	input.inf	USB\VID_1B1C&PID_0C1C&MI_00\6&1853d686&0&0000	SurpriseRemovalOK					
`

`0000.0014.0000.011.000.000.000.000.000	USB Input Device	HID (Human Interface Device)	Yes	Yes	No	No			2023-01-12 2:16:09 AM	2023-01-12 2:16:09 AM	1b1c	0c1c	1.00		03	00	00		FEATH3RBLADE-PC			7&85529ef&0	HidUsb	@input.inf,%HID.SvcDesc%;Microsoft HID Class Driver	hidusb.sys		(Standard system devices)				USB Input Device	10.0.22621.819	HID_Inst.NT	input.inf	USB\VID_1B1C&PID_0C1C&MI_01\6&1853d686&0&0001	SurpriseRemovalOK					
`

**Comment by EvanMulawski** [comment]
@Feath3rblade @Lithradus

Please try the beta.3 release and let me know what you see in `log.txt`.

https://github.com/EvanMulawski/FanControl.CorsairLink/releases/tag/v1.0.0-beta.3

**Comment by rumpleforeskin83** [comment]
While I'm not the original with this issue I am having the exact same. I've attached the log file and it seems to be recognizing my devices to some extent but not that they are supported.
[log.txt](https://github.com/EvanMulawski/FanControl.CorsairLink/files/10429615/log.txt)

**Comment by EvanMulawski** [comment]
@rumpleforeskin83 Thank you - I believe I know what the issue is now. A beta.4 release will be out shortly.

**Comment by EvanMulawski** [comment]
@Feath3rblade @rumpleforeskin83 @Lithradus

https://github.com/EvanMulawski/FanControl.CorsairLink/releases/tag/v1.0.0-beta.4

**Comment by rumpleforeskin83** [comment]
It recognizes all of my fans and sensors fine now, but it's causing my RGB in the fans to flicker off every half a second or so. Interesting.

**Comment by Lithradus** [comment]
I just got home from work and tried the latest build, unfortunately I'm still getting errors. Here is my log.txt. Maybe I'm running a different firmware version.


2023-01-16 7:09:18 PM: [CorsairLink] DeviceManager: Found 7 Corsair device(s)
  name=, devicePath=\\?\hid#virtualdevice&10&col01#2&3b8f46cf&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}
  name=, devicePath=\\?\hid#virtualdevice&10&col05#2&3b8f46cf&0&0004#{4d1e55b2-f16f-11cf-88cb-001111000030}
  name=, devicePath=\\?\hid#virtualdevice&10&col02#2&3b8f46cf&0&0001#{4d1e55b2-f16f-11cf-88cb-001111000030}\kbd
  name=, devicePath=\\?\hid#virtualdevice&10&col03#2&3b8f46cf&0&0002#{4d1e55b2-f16f-11cf-88cb-001111000030}\kbd
  name=, devicePath=\\?\hid#virtualdevice&10&col04#2&3b8f46cf&0&0003#{4d1e55b2-f16f-11cf-88cb-001111000030}
  name=CORSAIR iCUE Commander CORE, devicePath=\\?\hid#vid_1b1c&pid_0c1c&mi_01#7&387a1dd5&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}
  name=CORSAIR iCUE Commander CORE, devicePath=\\?\hid#vid_1b1c&pid_0c1c&mi_00#7&20b69190&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}

2023-01-16 7:09:18 PM: [CorsairLink] DeviceManager: Found 1 supported Corsair device(s)
  name=CORSAIR iCUE Commander CORE, devicePath=\\?\hid#vid_1b1c&pid_0c1c&mi_00#7&20b69190&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}

2023-01-16 7:09:18 PM: [CorsairLink] An exception occurred attempting to initialize device 'CORSAIR iCUE Commander CORE (630f0001801ccabae51f2af52091005f)' (\\?\hid#vid_1b1c&pid_0c1c&mi_00#7&20b69190&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}):
2023-01-16 7:09:18 PM: [CorsairLink] System.FormatException: The response was not valid.
   at CorsairLink.CommanderCoreDevice.EndpointResponse.ThrowIfInvalid()
   at CorsairLink.CommanderCoreDevice.InitializeSpeedChannels(EndpointResponse hardwareFixedSpeedPercentResponse)
   at CorsairLink.CommanderCoreDevice.Initialize()
   at CorsairLink.CommanderCoreDevice.Connect()
   at FanControl.CorsairLink.CorsairLinkPlugin.FanControl.Plugins.IPlugin.Initialize()
2023-01-16 7:09:20 PM: [CorsairLink] DeviceManager: Found 7 Corsair device(s)
  name=, devicePath=\\?\hid#virtualdevice&10&col01#2&3b8f46cf&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}
  name=, devicePath=\\?\hid#virtualdevice&10&col05#2&3b8f46cf&0&0004#{4d1e55b2-f16f-11cf-88cb-001111000030}
  name=, devicePath=\\?\hid#virtualdevice&10&col02#2&3b8f46cf&0&0001#{4d1e55b2-f16f-11cf-88cb-001111000030}\kbd
  name=, devicePath=\\?\hid#virtualdevice&10&col03#2&3b8f46cf&0&0002#{4d1e55b2-f16f-11cf-88cb-001111000030}\kbd
  name=, devicePath=\\?\hid#virtualdevice&10&col04#2&3b8f46cf&0&0003#{4d1e55b2-f16f-11cf-88cb-001111000030}
  name=CORSAIR iCUE Commander CORE, devicePath=\\?\hid#vid_1b1c&pid_0c1c&mi_01#7&387a1dd5&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}
  name=CORSAIR iCUE Commander CORE, devicePath=\\?\hid#vid_1b1c&pid_0c1c&mi_00#7&20b69190&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}

2023-01-16 7:09:20 PM: [CorsairLink] DeviceManager: Found 1 supported Corsair device(s)
  name=CORSAIR iCUE Commander CORE, devicePath=\\?\hid#vid_1b1c&pid_0c1c&mi_00#7&20b69190&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}

2023-01-16 7:09:20 PM: [CorsairLink] An exception occurred attempting to initialize device 'CORSAIR iCUE Commander CORE (630f0001801ccabae51f2af52091005f)' (\\?\hid#vid_1b1c&pid_0c1c&mi_00#7&20b69190&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}):
2023-01-16 7:09:20 PM: [CorsairLink] System.FormatException: The response was not valid.
   at CorsairLink.CommanderCoreDevice.EndpointResponse.ThrowIfInvalid()
   at CorsairLink.CommanderCoreDevice.InitializeSpeedChannels(EndpointResponse hardwareFixedSpeedPercentResponse)
   at CorsairLink.CommanderCoreDevice.Initialize()
   at CorsairLink.CommanderCoreDevice.Connect()
   at FanControl.CorsairLink.CorsairLinkPlugin.FanControl.Plugins.IPlugin.Initialize()
2023-01-16 7:09:22 PM: CorsairLink could not initialize or has no sensors.

**Comment by Feath3rblade** [comment]
The new beta works and recognizes all my fans and lets me control them. I'm also getting the same RGB flickering as @rumpleforeskin83. Moving to that thread now.
