### ISSUE TITLE
iCUE Link Titan 360 RX RGB AIO Support

### ISSUE THREAD

**Issue by iliketoprogram14** [EvanMulawski/FanControl.CorsairLink#202]
Please add support for the Titan AIO cooler.  There's also an error popup for the fan hub (at least I think it's the fan hub).

[CorsairLink.log](https://github.com/user-attachments/files/17938844/CorsairLink.log)

First run with the Titan AIO is on 11/28 in the logs.

**Comment by EvanMulawski** [comment]
Hi @iliketoprogram14, do you have the black or white color TITAN AIO?

I'm going to open a separate issue for the iCUE LINK Hub error you are seeing.

**Comment by EvanMulawski** [comment]
Opened #203 for the error present in your log file.

**Comment by iliketoprogram14** [comment]
I have the white one.

**Comment by EvanMulawski** [comment]
TITAN AIO support added in [v1.7.0-beta.4](https://github.com/EvanMulawski/FanControl.CorsairLink/releases/tag/v1.7.0-beta.4)

**Comment by iliketoprogram14** [comment]
Confirmed this is working - thanks so much for the quick turnaround!
