### ISSUE TITLE
iCUE LINK Hub: An error code was returned after sending the command.

### ISSUE THREAD

**Issue by EvanMulawski** [EvanMulawski/FanControl.CorsairLink#203]
Moved from #202:

> Please add support for the Titan AIO cooler. There's also an error popup for the fan hub (at least I think it's the fan hub).
> 
> [CorsairLink.log](https://github.com/user-attachments/files/17938844/CorsairLink.log)
> 
> First run with the Titan AIO is on 11/28 in the logs.

Author: @iliketoprogram14

**Comment by iliketoprogram14** [comment]
Let me know what other info I can provide to help debug.

**Comment by EvanMulawski** [comment]
@iliketoprogram14 Please try [v1.7.0-beta.4](https://github.com/EvanMulawski/FanControl.CorsairLink/releases/tag/v1.7.0-beta.4) and post your latest log file if the error occurs again. Thanks!

**Comment by iliketoprogram14** [comment]
Unfortunately I lost the repro as I ended up doing a fresh install of Windows.  If it reoccurs, will comment here.  Thank you!

**Comment by EvanMulawski** [comment]
Thanks - I'll reopen if you comment that it reoccurred.

**Comment by iliketoprogram14** [comment]
I installed SignalRGB to control lighting only, and the error returned.  I confirmed it's the cause of the error by restarting SignalRGB and observing the error pop back up.  SignalRGB should be compatible with FanControl with the CorsairLink plugin, for these fans and AIO, right?

Logs below.

[CorsairLink.log](https://github.com/user-attachments/files/17999535/CorsairLink.log)

**Comment by EvanMulawski** [comment]
@iliketoprogram14 Which version of SignalRGB are you running?

**Comment by iliketoprogram14** [comment]
signalrgb@2.4.36+8e8cdd2d

**Comment by EvanMulawski** [comment]
@iliketoprogram14 Can you open the device console in SignalRGB for the iCUE LINK Hub and post the contents when this issue is occurring? Thanks!

![image](https://github.com/user-attachments/assets/74b86259-2713-42be-9540-9a35a24a5a59)

**Comment by iliketoprogram14** [comment]
[SignalRGB Corsair plugin.info.txt](https://github.com/user-attachments/files/18000122/SignalRGB.Corsair.plugin.info.txt)

Attached.  100% repro when force reloading the Corsair plugin for SignalRGB.

I just realized, it looks like SignalRGB does not yet support this AIO (the fans show up but not the AIO LEDs), and it looks like it tries and fails to keep reading the AIO properties, so maybe that's the cause and I should just wait for full support...

Also worth noting that SignalRGB showed this notification: 
![image](https://github.com/user-attachments/assets/140c401a-b5a3-44a5-b479-ef84b8e15e78)

**Comment by EvanMulawski** [comment]
@iliketoprogram14 Yes, it looks like it's never closing the handle the Fan Control plugin needs due to that error in the log. I would recommend using the Report a Bug form in the bottom right of the SignalRGB window and provide this log with the exact model of the AIO.

The I2CBus/SMBus error appears to be unrelated - that's likely due to other software running which is preventing SignalRGB from connecting to other system devices.
