### ISSUE TITLE
H100i V2 coolent temp not showing up

### ISSUE THREAD

**Issue by SilkDragon** [EvanMulawski/FanControl.CorsairLink#206]
I'm unsure if I'm doing something wrong or if this one is not supported.
I'm trying to pull the coolant temp from my AIO, I got this plugin installed, iCUE is not running, the plugin is enabled, and I got the AIO plugged into USB. But it's still not showing up in the dropdown for temperature.

If I open up iCUE, I do see it there.

Let me know if I need to give you any more info, or if this isn't supported.

![Screenshot 2024-11-29 211622](https://github.com/user-attachments/assets/7e0d93d5-23d6-42f5-968a-8c6cfc8d5f76)
![Screenshot 2024-11-29 211823](https://github.com/user-attachments/assets/bcd58ca7-92f8-43c0-96e7-6ade6f5d1398)

**Comment by EvanMulawski** [comment]
Hi @SilkDragon, can you post your CorsairLink.log file(s)? (The log files are located in the Fan Control directory.) Thanks!

**Comment by SilkDragon** [comment]
Sure thing

[CorsairLink.log](https://github.com/user-attachments/files/17964245/CorsairLink.log)

**Comment by EvanMulawski** [comment]
Looks like you need to copy one more file for this device. Since you already have iCUE installed, follow just step 3 of the [SiUsbXpress driver guide](https://github.com/EvanMulawski/FanControl.CorsairLink?tab=readme-ov-file#siusbxpress-driver) and restart Fan Control.

**Comment by SilkDragon** [comment]
I guess I skipped that part, thank you so much it is now working.
