### ISSUE TITLE
Overwriting Default Device RGB

### ISSUE THREAD

**Issue by BenBart003** [EvanMulawski/FanControl.CorsairLink#207]
In iCue you can set a default RBG value that the device uses when iCue isn't running. When CorsairLink is on with no environment variables, it seems to address an RGB value

**Comment by EvanMulawski** [comment]
Hi @BenBart003, when the Fan Control plugin is in use the Corsair devices must be placed into "software" mode, which disables any stored/hardware profiles. You would need to use a software RGB application like SignalRGB or OpenRGB alongside Fan Control.
