### ISSUE TITLE
Add support for iCUE LINK VRM FAN

### ISSUE THREAD

**Issue by Zafiast** [EvanMulawski/FanControl.CorsairLink#209]
USB Packet Capture for [iCUE LINK CapSwap Module – VRM Fan](https://www.corsair.com/us/en/p/cpu-coolers/cw-9061014-ww/icue-link-aio-pump-cap-module-vrm-fan-cw-9061014-ww)
[icue_link_vrm_fancap.zip](https://github.com/user-attachments/files/18082852/icue_link_vrm_fancap.zip)

**Comment by EvanMulawski** [comment]
Hi @Zafiast, could you list the devices and quantities connected to your hubs? Thanks!

**Comment by Zafiast** [comment]
### Hub 1
3x QX120 Black
10x LX120 Black
TITAN 360 Black
VRM Fan

### Hub 2
3x iCUE LINK LIGHTING ADAPTER - controlling 8x LS Aurora strips and 2x RGB Strips 
3x iCUE LINK GPU RGB Adapter

**Comment by Zafiast** [comment]
Another capture for the HX1200i (2023) - CP-9020281
[hx1200i_2023_cp-9020281-na.zip](https://github.com/user-attachments/files/18099055/hx1200i_2023_cp-9020281-na.zip)

**Comment by EvanMulawski** [comment]
> Another capture for the HX1200i (2023) - CP-9020281 [hx1200i_2023_cp-9020281-na.zip](https://github.com/user-attachments/files/18099055/hx1200i_2023_cp-9020281-na.zip)

Thanks for the capture - created a separate issue for this device: #210

**Comment by EvanMulawski** [comment]
@Zafiast Please try [v1.7.0-beta.5](https://github.com/EvanMulawski/FanControl.CorsairLink/releases/tag/v1.7.0-beta.5)

If you encounter any issues, please reply with the latest CorsairLink.log file attached. Thanks!

**Comment by Zafiast** [comment]
Where do I find the CorsairLink.log file? My iCue LINK devices arent being detected
![image](https://github.com/user-attachments/assets/83792cb9-7db7-4838-b507-76f7928669e1)

**Comment by EvanMulawski** [comment]
The CorsairLink.log files are located in the Fan Control installation directory.

**Comment by EvanMulawski** [comment]
@Zafiast I think I found the issue - please try [v1.7.0-beta.6](https://github.com/EvanMulawski/FanControl.CorsairLink/releases/tag/v1.7.0-beta.6)

**Comment by Zafiast** [comment]
Works with no major issues.
