### ISSUE TITLE
Using with H115i RGB PRO XT reports: "CorsairLink could not initialize or has no sensors."

### ISSUE THREAD

**Issue by CalculonPrime** [EvanMulawski/FanControl.CorsairLink#24]
Running NET4.8 v147 of FanControl software, with version 1.0.0 of CorsairLink.  Log:

> 3/10/2023 2:40:45 AM: [CorsairLink] DeviceManager: Found 1 Corsair device(s)
>   name=H115iRGBPROXT, devicePath=\\?\hid#vid_1b1c&pid_0c21#7&37184169&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}
> 3/10/2023 2:40:45 AM: [CorsairLink] DeviceManager: Found 0 supported Corsair device(s)
> 3/10/2023 2:40:46 AM: [CorsairLink] DeviceManager: Found 1 Corsair device(s)
>   name=H115iRGBPROXT, devicePath=\\?\hid#vid_1b1c&pid_0c21#7&37184169&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}
> 3/10/2023 2:40:46 AM: [CorsairLink] DeviceManager: Found 0 supported Corsair device(s)
> 3/10/2023 2:40:46 AM: CorsairLink could not initialize or has no sensors.

I don't have the bloated iCUE software installed, but the pump is connected to a motherboard USB header.  Speed of the pump is at its factory default, and the radiator fans are plugged into the motherboard (and so controllable via Fan Control without CorsairLink).  Pump RPM is also fed into the motherboard via a 1-wire fan header connector (though that RPM is reported by FanControl as twice its actual value.)  What I need from CorsairLink is the coolant temperature sensor.

Note that I have HWiNFO64 (which was not running at the same time as FanControl), and it does show two sensors for the H115i - the coolant temperature, and the true (un-doubled) water pump rpm.  So i can read them there, but I need FanControl to have access to them.

**Comment by CalculonPrime** [comment]
OK, for whatever reason, Github "releases" includes betas, but the "latest" button takes you to the "actual" release and not the beta.  Anyway, when I try the beta, it appears to be working.

Though, one question.  In HWiNFO, I get tenths of a degree of temperature, but in FanControl + CorsairLilnk, I'm only getting whole degrees.  It matters a bit more for coolant than CPUs because the range is smaller.  Is this a FanControl issue or CorsairLink issue?

**Comment by EvanMulawski** [comment]
Moved your second question to #25. Closing this as it was self-resolved.
