### ISSUE TITLE
Fractional degrees for temperature sensors

### ISSUE THREAD

**Issue by EvanMulawski** [EvanMulawski/FanControl.CorsairLink#25]
> In HWiNFO64, I get tenths of a degree of temperature, but in FanControl + CorsairLilnk, I'm only getting whole degrees.  It matters a bit more for coolant than CPUs because the range is smaller.  Is this a FanControl issue or CorsairLink issue?

_Originally posted by @CalculonPrime in https://github.com/EvanMulawski/FanControl.CorsairLink/issues/24#issuecomment-1464041046_

**Comment by EvanMulawski** [comment]
@CalculonPrime Please try the new [v1.1.0-beta.3](https://github.com/EvanMulawski/FanControl.CorsairLink/releases/tag/v1.1.0-beta.3) release.

**Comment by EvanMulawski** [comment]
@CalculonPrime Just want to confirm if this is working as expected in the [v1.1.0-beta.3](https://github.com/EvanMulawski/FanControl.CorsairLink/releases/tag/v1.1.0-beta.3) release. Thanks!

**Comment by panda4k** [comment]
I'm running v1.1.0.-beta.3 and fractional degrees aren't working. I am using the H100i Elite Capellix for the record.
![image](https://user-images.githubusercontent.com/83919497/226655911-2e1d5a81-c30a-41be-a761-37f6a768e224.png)

**Comment by EvanMulawski** [comment]
Hi @panda4k, please try the new [v1.1.0-beta.4](https://github.com/EvanMulawski/FanControl.CorsairLink/releases/tag/v1.1.0-beta.4) release.

**Comment by panda4k** [comment]
> 

@EvanMulawski That brought back the fractional degrees, it's all good now - thank you!
