### ISSUE TITLE
Corsair Hydro Series H115i Extreme

### ISSUE THREAD

**Issue by jeyzones** [EvanMulawski/FanControl.CorsairLink#27]
device-variant
Corsair Hydro Series H115i Extreme
USB\VID_1B1C&PID_0C0A\7289_2.0

**Comment by EvanMulawski** [comment]
Hi @jeyzones, this device (`0c0a`) is equivalent to the H110i GT V2 model which is [not supported](https://github.com/EvanMulawski/FanControl.CorsairLink#device-support).

See also https://github.com/EvanMulawski/FanControl.CorsairLink/discussions/15#discussioncomment-4950855
