### ISSUE TITLE
Add support for the Corsair Commander Mini

### ISSUE THREAD

**Issue by Enterprise12nx01** [EvanMulawski/FanControl.CorsairLink#33]
I installed this but seems it doesnt detect any sensors for my Corsair Commander Mini

**Comment by EvanMulawski** [comment]
Hi @Enterprise12nx01, I am looking into this. The Commander Mini is an older device that uses a different communication protocol that is shared with the H80i, H100i, H100i GT, H110i, and H110i GT. If I make any progress, would you be willing to test private builds similar to what was done in #9? That's likely the only way this would get done as I do not own one of these devices.

**Comment by Enterprise12nx01** [comment]
Hi yes I would be willing to try it.
Any idea if this will let me be able to control the fans on the commander mini as well in fan control?

**Comment by VanStorm** [comment]
If you need an additional tester, I'd be willing to test it for you as well. Stumbled about this issue post while searching for a way to control the Corsair Commander Mini.

**Comment by EvanMulawski** [comment]
@Enterprise12nx01 @VanStorm Please try the attached build. This is just a test to determine if I am communicating with the device correctly; **nothing is implemented** except for reading the firmware version. Please post your log.txt file (or a relevant snippet) after running.

[FanControl.CorsairLink-CoolitDeviceExp-v20230415r001.zip](https://github.com/EvanMulawski/FanControl.CorsairLink/files/11240703/FanControl.CorsairLink-CoolitDeviceExp-v20230415r001.zip)

**Comment by VanStorm** [comment]
@EvanMulawski this is my log file with the plugin version you linked.
The firmware version 1.1.6 gets correctly detected.

[log.txt](https://github.com/EvanMulawski/FanControl.CorsairLink/files/11240929/log.txt)

**Comment by EvanMulawski** [comment]
@Enterprise12nx01 @VanStorm New build. Please post your log.txt file (or a relevant snippet) after testing.

[FanControl.CorsairLink-CoolitDeviceExp-v20230416r001.zip](https://github.com/EvanMulawski/FanControl.CorsairLink/files/11241377/FanControl.CorsairLink-CoolitDeviceExp-v20230416r001.zip)

**Comment by VanStorm** [comment]
@EvanMulawski It now correctly detects all 6 channels and seems to put the fan speed to around 40%.

[log.txt](https://github.com/EvanMulawski/FanControl.CorsairLink/files/11242122/log.txt)

**Comment by EvanMulawski** [comment]
@Enterprise12nx01 @VanStorm New build. Should be fully functional. Please post your log.txt file (or a relevant snippet) after testing.

[FanControl.CorsairLink-CoolitDeviceExp-v20230416r002.zip](https://github.com/EvanMulawski/FanControl.CorsairLink/files/11243084/FanControl.CorsairLink-CoolitDeviceExp-v20230416r002.zip)

**Comment by VanStorm** [comment]
@EvanMulawski I applied the new plugin version, however it doesn't apply the correct fan speeds. I set it to 80%, which should be around 800 RPM. The fans connected to the commander run at around 50%.

[log.txt](https://github.com/EvanMulawski/FanControl.CorsairLink/files/11243103/log.txt)

**Comment by EvanMulawski** [comment]
@Enterprise12nx01 @VanStorm New build. Please post your log.txt file (or a relevant snippet) after testing.

[FanControl.CorsairLink-CoolitDeviceExp-v20230416r003.zip](https://github.com/EvanMulawski/FanControl.CorsairLink/files/11243151/FanControl.CorsairLink-CoolitDeviceExp-v20230416r003.zip)

**Comment by VanStorm** [comment]
@EvanMulawski works fine now from what I can tell. Fans follow the speeds set in Fancontrol.
[log.txt](https://github.com/EvanMulawski/FanControl.CorsairLink/files/11244682/log.txt)

**Comment by EvanMulawski** [comment]
@VanStorm Appreciate the quick responses. I'll have an official pre-release up shortly.

**Comment by EvanMulawski** [comment]
Completed in [v1.2.0-beta.1](https://github.com/EvanMulawski/FanControl.CorsairLink/releases/tag/v1.2.0-beta.1)
