### ISSUE TITLE
Plugin does not work anymore...

### ISSUE THREAD

**Issue by Lebon14** [EvanMulawski/FanControl.CorsairLink#38]
Hi there.

I do not know what or who to blame here. I'm entirely clueless.

I have a H100i Platinum, a 680X Case with a Commander and its 3 fans + 3 QL and its Commander.
They failed to show up anymore in FanControl. I have issues for a few weeks now since it started to throw an error reading like "CorsairLink failed to initialize or has no sensor". Then, FanControl just wouldn't be able to detect or use any of my fans except my GPU. "Expected 14x sensors, found 3x". Using v147 as it seems to be the only version that, somehow, keeps my CPU cool.

If dev is active, I'm willing to elaborate or share all the old logs I have since the last couple of weeks. (500MB+)
Cheers.

**Comment by EvanMulawski** [comment]
Hi @Lebon14,

1. Just to confirm, the plugin is functional for you on v147 but not later versions?
2. What version of the plugin are you using?
3. Please provide a fresh log.txt or a snippet from the last run including the detected device list.

**Comment by Lebon14** [comment]
1. V147 is the version that does not make my PC run hot. Last night, I was on the latest version and I found out that my CPU was running at 88°C doing absolutely nothing. Also that's the only version where your FanControl doesn't throw and error specifically at CorsairLink.
2. The latest, 1.1.1
3. Sure. Here is the latest and then a backlog of logs.
[log.txt](https://github.com/EvanMulawski/FanControl.CorsairLink/files/11275087/log.txt)
Log archive, 438MB uncompressed:
https://we.tl/t-o1JFoO2plm (WinRAR, RAR5 archive)

Of note: I had uninstalled every RGB software I had then installed SignalRGB for like 2 weeks until last night when troubleshooting. I abandonned and re-installed iCue just for everything to work as intended and temps under control. Also, BIOS in my **Gigabyte X570 Aorus Master** is setup with the most basic automatic fan control ever.

Cheers.

**Comment by EvanMulawski** [comment]
@Lebon14 Can you post a screenshot of what you see in v147 Fan Control with the plugin installed and enabled? Do the fans and pump respond to manual control? I'm curious if that version is working properly or it just happens to be cooling to some degree.

**Comment by Lebon14** [comment]
Here:
https://i.gyazo.com/b44cdbe6edd6fb1fff23ed1f64567dc0.png

As you can see, the Corsair element just does not work (no rpm shown). I'll explain more later.

**Comment by Lebon14** [comment]
OK, so, despite what's showing, next to nothing works here but somehow still cool the CPU. Only the GPU and the PCH fan works as intended. Everything else is almost just there for show. At least, when I try to slide the % around, I don't notice the fans going any slower or faster. And, believe me, *all* fans are Corsair fans. The two that came with the H100i Platinum, the 3 LL that came with the 680X case and the extra 3 QL for the rest of the case. Each set of 3 fans are plugged into a controller for RGB purpose on top of having a 3-to-1 PWM header, plugged into Port 2 and 5 respectively. There's not enough separate headers on the motherboard otherwise. Of course, there's something plugged into CPU Fan. I think this controls the AIO pump but I'm not 100% sure. In the BIOS, everything is detected and show signs of activity. Without any fan controls in the OS (iCue or FanControl), you can hear the fans ramping up or down depending on the load. iCue picks up all controllers and AIO perfectly and controls them correctly. But, FanControl doesn't and neither does CorsairLink.

What was doing before that? I tried installing Windows for Android Subsystem and sideload an app. I had to install various extra module for Virtualization into my install of Windows 11 Pro and that's afterward I noticed the insane temperature.

However, issues started way before than. In fact, I don't think I ever had a "perfect" FanControl install at all. But, within the last month, it started to go south. Two weeks ago, I completely uninstall iCue so I could install SignalRGB because I wanted my RGB to control my RGB again. Before that, I was stopping my PC because I didn't want to deal with iCue again (not that I had issues but it's a resource hog). It's hard to pinpoint exactly when everything started and I hope that the logs provided more helpful info.

**Comment by EvanMulawski** [comment]
@Lebon14 Can you try the plugin version from this comment? This one has debug logging.

https://github.com/EvanMulawski/FanControl.CorsairLink/issues/9#issuecomment-1426879232

Please post the resulting log file after letting it run for 5 minutes.

**Comment by Lebon14** [comment]
Alright, here is the log file as you requested.
[log (debug).txt](https://github.com/EvanMulawski/FanControl.CorsairLink/files/11278654/log.debug.txt)
Hopefully this goes somewhere.

If needed, I can't open an issue on FanControl repo itself.

**Comment by EvanMulawski** [comment]
@Lebon14 It appears to be functioning as expected based on that log file. If you select "Pair controls and speeds automatically," are you able to control and monitor everything from the UI?

![image](https://user-images.githubusercontent.com/1044791/233230219-84192082-9217-41c0-a69f-b4f2a438433d.png)

**Comment by Lebon14** [comment]
In Identifying fans, changing the slider of the various fans does absolutely nothing. It does not change in anyway except for PCH Fan and the GPU.

**Comment by EvanMulawski** [comment]
@Lebon14 Can you send me another debug log after setting the fan speeds a few times using the sliders?

**Comment by Lebon14** [comment]
I haven't forgotten! Didn't want to deal with that while WFH. So, just got around to it. Here:
[log (debug 2).txt](https://github.com/EvanMulawski/FanControl.CorsairLink/files/11290833/log.debug.2.txt)

I went into "Identify Your Fans" and played with the levers a little bit. Only "System Fan #2" seems to be working and it seems to be related to my H100i Platinum fans. Huh. The *most* important ones. Haven't tried the GPU but I know they work. PCH still work as intended as well. The rest? Nope.

Would it be a Fan Control itself problem at this point?

**Comment by EvanMulawski** [comment]
@Lebon14 According to that log, the fan powers/speeds were never changed. They started out at 12.5% (and Quiet for the pump) (which is an unrelated bug I need to fix - they should start at 50%) and then get properly set to 50% (and Balanced for the pump). The only thing that appears to have changed is the pump mode, which briefly entered Performance mode and then went back to Balanced mode about two minutes in.

I'm curious why your other fans are reporting high/strange RPM (according to the screenshot you provided earlier). The Corsair LL/QL fans don't go above 1300/1500 RPM. Can you open Sensor Settings in the top-right menu and post a picture of the Sources tab? While you are there, try disabling the CPU and Motherboard sources and see if that solves the issue with the H100i.

**Comment by Lebon14** [comment]
Here's the sensor setting screenshot:
https://i.gyazo.com/cbbc1ba1f1b4762a927804e8917ed7d7.png

I unchecked the CPU and Motherboard from the sensors and this happened:
https://www.youtube.com/watch?v=sF6BkwXaTJc (1min)

Here's a log of what's happening when I removed the CPU / motherboard then try to change the % of the fans in the identify menu: [log (debug 3).txt](https://github.com/EvanMulawski/FanControl.CorsairLink/files/11300151/log.debug.3.txt)

So, in the end, it failed spectacularly as nothing worked after. Trying to close the app without saving the settings crashed the app entirely. I had to kill it in Task Manager.

**Comment by EvanMulawski** [comment]
@Lebon14 Please try the following:

1. Quit Fan Control, navigate to the directory where `FanControl.exe` is located and delete or move `userConfig.json` from the `Configurations` subdirectory.
2. Delete or move the existing `log.txt` file.
3. Launch Fan Control. Do not run any automated/assisted setup yet if prompted.
4. From the right side menu, open Sensor Settings, uncheck all Sources except **NvApiWrapper** and **CorsairLink**, and click OK.
5. From the left side menu, check/enable **Show hidden cards** and uncheck/disable **Hide fan speed cards**. Close the side menu.
6. Save this configuration using the right side menu.
7. Save a screenshot of the Fan Control UI at this point (enlarge the window if necessary).
8. For the H100i pump and fans under the Controls section, click the three dots, select **Pair speed sensor...**, click the now-colored fan icon of the speed sensor with a matching name.
9. Toggle the switch on the H100i pump and fan control cards to the on/colored position if they are not already.
10. From the left side menu, uncheck/disable **Show hidden cards** and check/enable **Hide fan speed cards**. Close the side menu.
11. Save this configuration using the right side menu.
12. Save a screenshot of the Fan Control UI at this point (enlarge the window if necessary).
13. For the H100i pump and fans under the Controls section, click the three dots, check/enable **Manual control**.
14. For the H100i pump and fans under the Controls section, play around with the slider to make sure the speeds change accordingly.
15. If something is not working as expected, post the two screenshots and the log file. Otherwise, you can set up and assign fan curves.

**Comment by Lebon14** [comment]
Point 7 screenshot: https://i.gyazo.com/85a6903f043d8bf40070dc51041dd250.png
Point 12 screenshot: https://i.gyazo.com/d402b38eb59cfaa8795db18a3e6cebf3.png

OK, during point 14, the pump and fans seems to work correctly. I don't know why they do now but they do.
Here's the latest log anyway: [log (debug 4).txt](https://github.com/EvanMulawski/FanControl.CorsairLink/files/11302342/log.debug.4.txt)

I'd like to know what's going on though... however, my case fans are still aren't detected and controlable. The good part is that, well, CPU temps can be controlled.

**Comment by EvanMulawski** [comment]
@Lebon14 Alright, so the plugin is functional. Now you can try re-enabling the CPU and Motherboard sources in Sensor Settings (and select "Refresh sensors detection" from the right side menu if necessary). That should bring in the PCH fan and the fans connected to the motherboard headers (and additional temperature sensors).

**Comment by Lebon14** [comment]
Yeah, all good. I restored a previous userconfig because it had all my curves in it but I knew what wrong (auto-pairing fudges up the pairing) so I fixed it and I went on my merry day.. Welp, I know what actually happens now.
