### ISSUE TITLE
Fan RGB flickering

### ISSUE THREAD

**Issue by EvanMulawski** [EvanMulawski/FanControl.CorsairLink#4]
> It recognizes all of my fans and sensors fine now, but it's causing my RGB in the fans to flicker off every half a second or so. Interesting.

_Originally posted by @rumpleforeskin83 in https://github.com/EvanMulawski/FanControl.CorsairLink/issues/2#issuecomment-1384612770_

**Comment by EvanMulawski** [comment]
@rumpleforeskin83 

1. What are you using for RGB control?
2. Please post `log.txt` (or part of it).

**Comment by rumpleforeskin83** [comment]
Nothing at all controlling the RGB. Everything is the default setting that applies when iCue is not running and handling the lighting. I am going to work on setting up SignalRGB but as of now RGB is not being controlled by anything except the default setting in the commander core XT.

[log.txt](https://github.com/EvanMulawski/FanControl.CorsairLink/files/10429710/log.txt)

**Comment by rumpleforeskin83** [comment]
After getting Signal RGB partially setup the issue has disappeared and everything seems to be fine. It may have been because nothing was controlling the lighting. Everything seems in be in good working order.

**Comment by rumpleforeskin83** [comment]
When FanControl is running SignalRGB is unable to change the lighting, when I close FanControl SignalRGB works as expected. It seems the 2 programs trying to access the commander core at the same time is causing a conflict maybe.

**Comment by EvanMulawski** [comment]
Can you post `log.txt` again? Would like to see if there are any errors there that would explain the conflict.

**Comment by rumpleforeskin83** [comment]
There is indeed errors. SignalRGB gives similar, Operation failed whenever trying to send a color signal to LEDs if FanControl is running.

[log.txt](https://github.com/EvanMulawski/FanControl.CorsairLink/files/10429785/log.txt)

**Comment by rumpleforeskin83** [comment]
Both programs operate as expected when running independently, it's when they both are trying to access the commander core at the same time that they fail.

**Comment by EvanMulawski** [comment]
I don't think there's a way to solve this. The protocols for the Corsair Commander devices are not designed for multiple communication channels. You would need to run the RGB program by itself, store the lighting configuration on the Commander, and then exit the RGB program.

**Comment by rumpleforeskin83** [comment]
I was kind of thinking that there's no way for both to communicate with the commander at the same time. Regardless you're doing the community a great favor and it's really appreciated.

**Comment by EvanMulawski** [comment]
Reopening. Having Fan Control running with this plugin and a hardware lighting profile causes the lights to turn on and off repeatedly. Investigating.

**Comment by EvanMulawski** [comment]
@Heal-Bot Thank you for all of that information and the time you spent laying it out - I really appreciate it! I will be testing all of this shortly. 

I did notice that mutex defined in `Corsair.Public.dll` (`CorsairLink4.Public.Synchronization.CorsairDevicesGuard`) - but also noticed it wasn't really used anywhere apart from firmware/bootloader operations. The one downside to supporting this is that it will require referencing `System.Threading.AccessControl` to configure `MutexSecurity`, which requires additional DLL's that will complicate plugin installation. I may need to target `net48` instead of `netstandard2.0`.

**Comment by rumpleforeskin83** [comment]
I hate to clog the discussion but feel free to call me out if you get a new
beta put together and would like someone to test it.

**Comment by EvanMulawski** [comment]
This should be fixed in **v1.0.0-beta.6**.
