### ISSUE TITLE
Add support for HXi/RMi power supplies

### ISSUE THREAD

**Issue by HarukiCZ** [EvanMulawski/FanControl.CorsairLink#42]
Dear Development Team,

I would like to request the addition of support for the Corsair HX850i power supply in the Fan Control plugin. It would be greatly beneficial to be able to control the fans of the power supply, monitor its temperatures, and view the current fan speed.

As a user of Fan Control, I believe this addition would enhance the overall experience for users who have this specific power supply.

Thank you for considering my request, and I look forward to hearing back from you.

Best regards,
Haruki_

**Comment by EvanMulawski** [comment]
Hi @HarukiCZ, would you be able to test development builds and provide log files as I work on this? That's likely the only way this would get done as I do not own one of these devices.

**Comment by HarukiCZ** [comment]
Ah, I'm just now discovering that GitHub didn't send that message. Of course, I'm very happy to help test development builds of this plugin.

**Comment by Superino45** [comment]
if you want available, corsair ax1600i

**Comment by chjohans** [comment]
I have a Corsair RM1000i PSU and I'll be willing to test a development build as well if that helps

**Comment by EvanMulawski** [comment]
Thanks everyone. I'll see what I can do and post a development build here for everyone to test when I have something.

(Note: The AXi PSU series is a different USB device class and support for that isn't possible at this time.)

**Comment by DfrostX** [comment]
I also have an Corsair HX850i. It would be amazing to be able to control my psu fan within fancontrol instead of relying on liquidctl scripts!

**Comment by EvanMulawski** [comment]
@HarukiCZ @Burn1ngShad0w @chjohans @DfrostX Please test the attached build. Logs and screenshots would be appreciated.

[FanControl.CorsairLink-PsuDeviceExp-v20230615r001.zip](https://github.com/EvanMulawski/FanControl.CorsairLink/files/11752703/FanControl.CorsairLink-PsuDeviceExp-v20230615r001.zip)

**Comment by chjohans** [comment]
My testing above was done with v20230615r001.

I re-tested with  v20230615r002 and I didn't see any of the issues I describe. But I don't see any sensors for the PSU either, no fan control, no speed sensor and no temperature sensor(s). But it still says it found my PSU in the logfile. See the attached l.ogfile.

[log.15-06-2023-3.txt](https://github.com/EvanMulawski/FanControl.CorsairLink/files/11754157/log.15-06-2023-3.txt)

**Comment by DfrostX** [comment]
Hi EvanMulawski,

Thanks for the test build! In my case, with r002, I also got "CorsairLink could not initialize or has no sensors"

No sensor/fan speed or control appeared (obviously since the plugin did not initialize).

Looking at the log, I see that a devide was detected, but then a bunch of errors.

[log.txt](https://github.com/EvanMulawski/FanControl.CorsairLink/files/11763900/log.txt)

**Comment by EvanMulawski** [comment]
@chjohans @DfrostX New build.

[FanControl.CorsairLink-PsuDeviceExp-v20230615r003.zip](https://github.com/EvanMulawski/FanControl.CorsairLink/files/11764045/FanControl.CorsairLink-PsuDeviceExp-v20230615r003.zip)

**Comment by chjohans** [comment]
That was a bit better, now it correctly finds and names my PSU RM1000i. I have the fan control and the fan speed. But I cannot control the PSU fan speed, it just stays at zero rpm. Also the two temperature sensors for my PSU is just showing NaN.

I also did a "refresh" a few times, a few times I lost a bunch of sensors and at least one time it said "LibreHardwareMonitor could notr initialize or has no sensors".

After doing "refresh" a few times FanCOntrol would hang and I had to kill it in Task Manager.

Log file attached.

[log.txt](https://github.com/EvanMulawski/FanControl.CorsairLink/files/11764213/log.txt)

**Comment by DfrostX** [comment]
Pretty much the same as chjohans

Iit correctly finds and names my PSU. I have the fan control and the fan speed. But I cannot control the PSU fan speed, it just stays at zero rpm. Also the two temperature sensors for my PSU is just showing NaN.

Upon closing FanControl, it stayed somehow in the background and could not be started again until I killed it in Task Manager.

I also noticed tha the logfile was growinging indefinitely until I closed FanControl.

[log.txt](https://github.com/EvanMulawski/FanControl.CorsairLink/files/11765062/log.txt)

![Capture d’écran (29)](https://github.com/EvanMulawski/FanControl.CorsairLink/assets/70845235/0e88f486-d61a-4ca5-a8d3-62353e5b9930)

**Comment by EvanMulawski** [comment]
@DfrostX @chjohans If you disable this plugin in Sensor Settings (or use an official release version) and then enable the Corsair PSU support (also in Sensor Settings), do the RPM and temp sensors show up and function?

**Comment by DfrostX** [comment]
> @DfrostX @chjohans If you disable this plugin in Sensor Settings (or use an official release version) and then enable the Corsair PSU support (also in Sensor Settings), do the RPM and temp sensors show up and function?

Yes it does, sensor RPM and Temp

![Capture d’écran (32)](https://github.com/EvanMulawski/FanControl.CorsairLink/assets/70845235/1fb9b315-b1fa-4e89-b6ab-8bdedeba4614)

**Comment by chjohans** [comment]
> @DfrostX @chjohans If you disable this plugin in Sensor Settings (or use an official release version) and then enable the Corsair PSU support (also in Sensor Settings), do the RPM and temp sensors show up and function?

Yes, it does.

**Comment by EvanMulawski** [comment]
@chjohans @DfrostX New build.

[FanControl.CorsairLink-PsuDeviceExp-v20230618r001.zip](https://github.com/EvanMulawski/FanControl.CorsairLink/files/11780721/FanControl.CorsairLink-PsuDeviceExp-v20230618r001.zip)

**Comment by chjohans** [comment]
Seems to be stuck in an initialization loop:
![snap003734](https://github.com/EvanMulawski/FanControl.CorsairLink/assets/24390228/ab5a90a4-1506-42f0-a320-ed9a106f0fbb)
![snap003735](https://github.com/EvanMulawski/FanControl.CorsairLink/assets/24390228/bbf84ddf-6c47-49d6-8937-0a5fa1b895ea)
[log.txt](https://github.com/EvanMulawski/FanControl.CorsairLink/files/11780800/log.txt)

I'll be away from this computer for a couple of months so I won't be able to do any more testing for now.

**Comment by Burn1ngShad0w** [comment]
RPM Sensor shows up but control is not working.

[log_18-06-2023.txt](https://github.com/EvanMulawski/FanControl.CorsairLink/files/11780865/log_18-06-2023.txt)

**Comment by DfrostX** [comment]
> @chjohans @DfrostX New build.
> 
> [FanControl.CorsairLink-PsuDeviceExp-v20230618r001.zip](https://github.com/EvanMulawski/FanControl.CorsairLink/files/11780721/FanControl.CorsairLink-PsuDeviceExp-v20230618r001.zip)

Well this one works for me!

Sensor temp + rpm and also ability to control. RPM % seems to be matching liquilctl (ex 30%= 550rpm - 100% = 1500rpm). Closing FanControl will reset the fan to 0rpm and close properly. Rebooting the PC and having FanControl start with session seems to nitialize the PSU/ control correctly.

With that said, the log is growing at a pace of 12 lines per second. See below.

[log.txt]
(https://github.com/EvanMulawski/FanControl.CorsairLink/files/11781698/log.txt)

Is there any way not to verbose all those READ/WRITE lines? This is going to create wear on my NVE drive if I let this on all the time.

**Comment by chjohans** [comment]
> Seems to be stuck in an initialization loop: ![snap003734](https://user-images.githubusercontent.com/24390228/246647990-ab5a90a4-1506-42f0-a320-ed9a106f0fbb.png) ![snap003735](https://user-images.githubusercontent.com/24390228/246647994-bbf84ddf-6c47-49d6-8937-0a5fa1b895ea.png)
> 
> I had to kill FanControl with the Task Manager, and I had to reboot after this.
> 
> I'll be away from this computer for a couple of months so I won't be able to do any more testing for now.
> 
> [log.txt](https://github.com/EvanMulawski/FanControl.CorsairLink/files/11780800/log.txt)

My bad, please disregard the above. I had accidentally left SUpport for Corsair PSU on in FanControl since testing with that to answer a question above.

Wo when turning that off the result was much better. I see my PSU temperature sensors (two of them), the fans peed and the fan control. I can manually control the PSU fan, at 100% it runs at about 1500 RPM which sounds about right.

But at 0 percent the fan is still running at 660 RMP, see the next screenshot:
![snap003737](https://github.com/EvanMulawski/FanControl.CorsairLink/assets/24390228/e7ea490b-79ea-4ae4-a020-413cd9daf785)

Usually my PSU fan is off at 0 RMP since it's on "silent mode". But I noticed that when starting FanControl this time my PSU fan speed was sitting at 800+ RMP, and after playing with manually controlling the speed I quit FanControl and the PSU fan speed would return to rpm,

Here is a log file:
[log.txt](https://github.com/EvanMulawski/FanControl.CorsairLink/files/11782056/log.txt)

Also, if I try to start FanCOntrol a 2nd time after stopping it with this plugin enabled it will not start, it will just show this error message:
![image](https://github.com/EvanMulawski/FanControl.CorsairLink/assets/24390228/bcb9ada4-9a46-4e1c-8921-1ba6e9da9d61)
Ane here is the log file for that error:
[log.txt](https://github.com/EvanMulawski/FanControl.CorsairLink/files/11782061/log.txt)

I have to reboot for FanControl to work again after this.

**Comment by chjohans** [comment]
> > Seems to be stuck in an initialization loop: ![snap003734](https://user-images.githubusercontent.com/24390228/246647990-ab5a90a4-1506-42f0-a320-ed9a106f0fbb.png) ![snap003735](https://user-images.githubusercontent.com/24390228/246647994-bbf84ddf-6c47-49d6-8937-0a5fa1b895ea.png)
> > I had to kill FanControl with the Task Manager, and I had to reboot after this.
> > I'll be away from this computer for a couple of months so I won't be able to do any more testing for now.
> > [log.txt](https://github.com/EvanMulawski/FanControl.CorsairLink/files/11780800/log.txt)
> 
> My bad, please disregard the above. I had accidentally left "Support for Corsair PSU" on in FanControl since testing with that to answer a question above.
> 
> So when turning that off the result was much better. I see my PSU temperature sensors (two of them), the fan speed, and the fan control. I can manually control the PSU fan, at 100% it runs at about 1500 RPM which sounds about right.
> 
> But at 0 percent the fan is still running at 660 RMP, see the next screenshot: ![snap003737](https://user-images.githubusercontent.com/24390228/246676490-e7ea490b-79ea-4ae4-a020-413cd9daf785.png)
> 
> Usually, my PSU fan is off at 0 RMP since it's on "silent mode". But I noticed that when starting FanControl this time my PSU fan speed was sitting at 800+ RMP, and after playing with manually controlling the speed I quit FanControl and the PSU fan speed would return to rpm,
> 
> Here is a log file: [log.txt](https://github.com/EvanMulawski/FanControl.CorsairLink/files/11782056/log.txt)
> 
> Also, if I try to start FanCOntrol a 2nd time after stopping it with this plugin enabled it will not start, it will just show this error message: ![image](https://user-images.githubusercontent.com/24390228/246676710-bcb9ada4-9a46-4e1c-8921-1ba6e9da9d61.png)
> 
> And here is the log file for that error: [log.txt](https://github.com/EvanMulawski/FanControl.CorsairLink/files/11782061/log.txt)
> 
> I had to reboot for FanControl to work again after this. This can be re-produced and happens every time.

Turns out the reason I had to reboot was that FanCOntrol.exe was stuck with no GUI, killing the process works just as well. :)

**Comment by EvanMulawski** [comment]
@DfrostX

That logging will be disabled/optional in an official release, but it's necessary during development so I can see all of the device communication.

What does the RPM sensor read if you set the fan speed to 0%?

**Comment by DfrostX** [comment]
> @DfrostX
> 
> That logging will be disabled/optional in an official release, but it's necessary during development so I can see all of the device communication.
> 
> What does the RPM sensor read if you set the fan speed to 0%?

Gotcha

30% is the duty cycle, of software control, so setting it to 0% will result in the fan staying a 550rpm (30%). Liquidctl behave the same. Silent mode is only possible in hardware control mode, so you would have to reinitialize the unit in hardware mode when set to 0% for it to achieve 0 rpm "manually".

Source [https://github.com/liquidctl/liquidctl/blob/main/docs/corsair-hxi-rmi-psu-guide.md#fan-speed](url)

**Comment by EvanMulawski** [comment]
@DfrostX This new build should return control to the PSU if it's set to 0% in Fan Control.

[FanControl.CorsairLink-PsuDeviceExp-v20230618r002.zip](https://github.com/EvanMulawski/FanControl.CorsairLink/files/11782343/FanControl.CorsairLink-PsuDeviceExp-v20230618r002.zip)

**Comment by DfrostX** [comment]
> @DfrostX This new build should return control to the PSU if it's set to 0% in Fan Control.
> 
> [FanControl.CorsairLink-PsuDeviceExp-v20230618r002.zip](https://github.com/EvanMulawski/FanControl.CorsairLink/files/11782343/FanControl.CorsairLink-PsuDeviceExp-v20230618r002.zip)

Nice! The 0 rpm now works perfectly for me except...

I think I found the condition needed for the crash that chjohans has been experiencing

If I set the fan to 0%
Save the config
Close Fan control (close fine)
Start FanControl (so config load 0%)
Close FanControl

At this point, the gui will close and the icon disapear, but it will stay loaded in memory. I have to force close it from task manager to be able to start it correctly or else I get the same error message.

Saving the config at 30% will not create the same issue and FanControl will close/start properly

See the log of this behaviour happening (I started/closed/force closed FanControl 3 times in a row)

[log.txt](https://github.com/EvanMulawski/FanControl.CorsairLink/files/11782397/log.txt)

**Comment by EvanMulawski** [comment]
@DfrostX Thanks for the info. New build - let me know if it fixes that problem.

[FanControl.CorsairLink-PsuDeviceExp-v20230618r003.zip](https://github.com/EvanMulawski/FanControl.CorsairLink/files/11782504/FanControl.CorsairLink-PsuDeviceExp-v20230618r003.zip)

**Comment by DfrostX** [comment]
@EvanMulawski it indeed does, but it breaks the 0 rpm mode does not work anymore with this build

**Comment by EvanMulawski** [comment]
@DfrostX New build.

[FanControl.CorsairLink-PsuDeviceExp-v20230618r004.zip](https://github.com/EvanMulawski/FanControl.CorsairLink/files/11782602/FanControl.CorsairLink-PsuDeviceExp-v20230618r004.zip)

**Comment by DfrostX** [comment]
@EvanMulawski "CorsairLink could not initialize or has no sensors"

[log.txt](https://github.com/EvanMulawski/FanControl.CorsairLink/files/11782615/log.txt)

**Comment by EvanMulawski** [comment]
@DfrostX New build.

[FanControl.CorsairLink-PsuDeviceExp-v20230618r005.zip](https://github.com/EvanMulawski/FanControl.CorsairLink/files/11782628/FanControl.CorsairLink-PsuDeviceExp-v20230618r005.zip)

**Comment by DfrostX** [comment]
@EvanMulawski I think you nailed it wih the latest. 

I will let it run it for a bit to see if other type of issue arise, but for now, I'm happy to report that all functionnality of the HX850i are fully working with with this build.

**Comment by EvanMulawski** [comment]
Closing this as support has been added in the **v1.3.0-beta.1** pre-release.
