### ISSUE TITLE
FanControl resets Hardware RGB on Core XT ?

### ISSUE THREAD

**Issue by arlo-infinity** [EvanMulawski/FanControl.CorsairLink#44]
When I use iCue to set some Hardware RGB setting to the 3pin RGB on the Core XT (the default behaviour that should run when iCue is not open), and then close iCue and shut down all iCue and corsair background processes the Hardware RGB setting is fine.   

However, when I open Fan Control it shuts down the RGB completely.    Is this expected behavior? Am I missing something obvious?  It seems pretty basic but I couldn't find the same issue mentioned.

**Comment by EvanMulawski** [comment]
Hi @arlo-infinity, the devices only operate in software mode (footnote 1 on the device support matrix) since the Fan Control app controls the speeds and reads the temperature sensors every second. There isn't a way to have the devices in hardware mode for lighting and software mode for cooling as Corsair expects everyone to use iCUE. You will need to control the lighting using RGB software that respects the well-known Corsair communication mutex/lock (e.g. OpenRGB) to ensure the device is always in a valid state.

**Comment by arlo-infinity** [comment]
Thanks for responding so swiftly @EvanMulawski , and for making everything work so seamlessly with Corsair controllers.  It is very much appreciated by everyone I'm sure.

I actually stumbled accross SignalRGB last night right after posting here because I found the earlier thread where you fixed the flickering incompatibility between SignalRGB and FanControl.CorsairLink.  Great work and thanks for all  your efforts!

Incidentally, off topic, but do you know anything about the Razer PWM fan controller (which also uses a USB interface) or if anyone is working on a FanControl plugin for it?  It looks like a solid product with 8 PWM channels but I went with Corsair because of your plugin.

**Comment by EvanMulawski** [comment]
> Incidentally, off topic, but do you know anything about the Razer PWM fan controller (which also uses a USB interface) or if anyone is working on a FanControl plugin for it? It looks like a solid product with 8 PWM channels but I went with Corsair because of your plugin.

Doesn't look like a plugin exists for that, though it should be possible to create one assuming it's a standard HID device and not something like UART/USBXpress (which is why some of the older Corsair Hydro liquid coolers are explicitly not supported). I might look into it if there's enough demand.

**Comment by arlo-infinity** [comment]
> Doesn't look like a plugin exists for that, though it should be possible to create one assuming it's a standard HID device and not something like UART/USBXpress (which is why some of the older Corsair Hydro liquid coolers are explicitly not supported). I might look into it if there's enough demand.

I've seen another thread on the main FanControl Github asking about it, and I'm sure we can't be the only ones.   I'd be more than happy to donate in support of you getting the device for testing and for your time  --- I don't know the best way to try and drum of support other than perhaps starting another repo and putting it on the main plugins page.   I'd also be willing to provide feedback and testing if you do decide to look into it.

**Comment by EvanMulawski** [comment]
@arlo-infinity Do you already own the Razer PWM Fan Controller?

**Comment by arlo-infinity** [comment]
> @arlo-infinity Do you already own the Razer PWM Fan Controller?

Yes, I have one which I was using before I picked up a Corsair unit.
