### ISSUE TITLE
Issue when  running this plugin and SignalRGB

### ISSUE THREAD

**Issue by chjohans** [EvanMulawski/FanControl.CorsairLink#55]
Your readme says that this plugin is compatible with SingalRGB v 2.2.29+. In my experience that is not the case. As soon as I start SingnalRGB v2.2.32 my COmmander Pro temperature sensors go haywire, the reading will alternate between something that seems to be the correct temperature, 0 C, and NaN. I'm attaching the log but it doesn't say anything as nothing is logged when this is happening.

My temperature sensors recover as soon as I stop SignalRGB, so no reboot was needed.

[log.txt](https://github.com/EvanMulawski/FanControl.CorsairLink/files/11771040/log.txt)

**Comment by EvanMulawski** [comment]
Hi @chjohans, try enabling "Monitoring Compatibility Mode" in the device settings within SignalRGB - though I'm not sure why that would be necessary as they have implemented the well-known mutex that this plugin also uses to synchronize communication (see [version 2.2.29 change log](https://docs.signalrgb.com/changelogs/2-2-29)). You may want to post this question in their [support forum](https://forum.signalrgb.com/c/support/5).

**Comment by chjohans** [comment]
Thanks, enabling "Monitoring Compatibility Mode" for my Commander Pro under devices in SignalRGB did the trick. Once enable the temp sensors in FanControl instantly recovered. If I disable this option again the same sensors instantly go haywire. I can reproduce this every time I toggle that switch. So I guess they don't use the mutex unless this option is checked, makes no sense to me but that seems to be how they did it.
