### ISSUE TITLE
Add support for AXi power supplies

### ISSUE THREAD

**Issue by EvanMulawski** [EvanMulawski/FanControl.CorsairLink#57]
Support for AXi-series PSUs is currently in progress. If you would like to help test development builds, please leave a comment with your **AXi model** (e.g. AX1600i) and the **hardware product ID (PID)** (e.g. `1c11`). To find your hardware product ID, ensure your device is connected via USB and use Device Manager or [USBDeview](https://www.nirsoft.net/utils/usbdeview-x64.zip).

/cc @Superino45 @EduardoPimentel

**Comment by EduardoPimentel** [comment]
Model: AX860i
Product ID (PID): 1c00

**Comment by EvanMulawski** [comment]
@EduardoPimentel Build attached. Please go through the README in the `Corsair-SiUsbXpress-Driver` directory. If you encounter any issues, please reply with the latest `CorsairLink.log` file attached.

[FanControl.CorsairLink-AxiPsu-v20230630r001.zip](https://github.com/EvanMulawski/FanControl.CorsairLink/files/11923284/FanControl.CorsairLink-AxiPsu-v20230630r001.zip)

**Comment by EvanMulawski** [comment]
Added in v1.3.0-beta.3
