### ISSUE TITLE
No FanControl.CorsairLink.dll?

### ISSUE THREAD

**Issue by Jorrdddyy** [EvanMulawski/FanControl.CorsairLink#63]
I've tried a few different version of the release versions but can not find a file called 'FanControl.CorsairLink.dll'. Closest I can find is 'FanControl.CorsairLink.csproj' or 'FanControl.CorsairLink.sln'.

**Comment by DfrostX** [comment]
See link below

https://github.com/EvanMulawski/FanControl.CorsairLink/releases

Under "assets", download the .zip file, the one you need is in it.

And also, make sure you are using the .net 4.8 version of FanControl. The plugin will not work with the 7.0 version
