### ISSUE TITLE
Request to add support

### ISSUE THREAD

**Issue by zenosisalive** [EvanMulawski/FanControl.CorsairLink#64]
Request for support added for Hydro H100i GTX | AIO | 0c03 please

**Comment by EvanMulawski** [comment]
Hi @zenosisalive, would you be able to test development builds? I may have this working in 1-2 weeks.

**Comment by zenosisalive** [comment]
Hi Evan,

Yes, I'd be happy to. Just let me know what you need :)

Thanks,

Paul Honour

**Comment by EvanMulawski** [comment]
Closing in favor of #67
