### ISSUE TITLE
Causing stutter in SignalRGB

### ISSUE THREAD

**Issue by IndyPilot** [EvanMulawski/FanControl.CorsairLink#65]
Thank you for the plugin! I've noticed when using the plugin with FanControl, it is cause a stutter with the lighting in SignalRGB. When I remove the plugin, the stutter goes away. Any way to fix it?

**Comment by EvanMulawski** [comment]
Hi @IndyPilot, can you post the `log.txt` or `CorsairLink.log` file located in the Fan Control directory?

**Comment by IndyPilot** [comment]
[CorsairLink.log](https://github.com/EvanMulawski/FanControl.CorsairLink/files/12062470/CorsairLink.log)

I cannot find a log.txt file. This is a new install of FanControl so maybe one hasn't been generated? Or is there a way to export it?

I dont know if this helps, but I have found a situation where it does and doesn't stutter. I'll try to explain the best I can:

1. All fans are setup and pair - Stutter
2. I create a Flat curve with a percentage, say 30%, and assign it to all fans - Stutter
3. I go to the flat curve, highlight the 30% and change it to another value - No sutter
4. I click outside of the fan curve box to active the new percentage - Stutter

It seems as if anytime the curve is in an active input mode, the stutter goes away. But as soon as you "apply" the edit, the stutter comes back.

**Comment by EvanMulawski** [comment]
What version of SignalRGB are you using?

Can you enable debug logging and post the `CorsairLink.log` file after reproducing? To enable debug logging, set the `FANCONTROL_CORSAIRLINK_DEBUG_LOGGING_ENABLED` Windows environment variable to `1` and restart Fan Control. (When done, set it to `0` and restart Fan Control to disable.)

**Comment by IndyPilot** [comment]
SignalRB V2.2.32.0

I'm not 100% I did the debugging log correctly. Please let me know if not.

[CorsairLink.log](https://github.com/EvanMulawski/FanControl.CorsairLink/files/12062615/CorsairLink.log)

**Comment by EvanMulawski** [comment]
How often do you observe the RGB stutter? Would you say it "pauses" or "flickers"?

**Comment by IndyPilot** [comment]
Definitely a pause, not a flicker. The best way I can describe is animations are smooth for 2sec, couple millisecond pause, smooth for 2sec, couple millisecond pause, repeat.

2 sec may be generous.

**Comment by IndyPilot** [comment]
Update: The stutter has gone away for the time being. Honestly, I have no clue why or if I did anything. Software-wise, I really haven't changed anything on my system. I'll let you know if it returns.

**Comment by IndyPilot** [comment]
Update 2: Unfortunately, the issue has returned with the same symptoms.

**Comment by EvanMulawski** [comment]
I can reproduce this during fast color/brightness transitions. I don't believe I can do anything to improve it because the device access is shared between Fan Control and SignalRGB. SignalRGB has to constantly send significant amounts of data to the device as the RGB is software-controlled.

**Comment by IndyPilot** [comment]
Thanks for at least looking into it!
