### ISSUE TITLE
Add support for the Asetek Hydro liquid cooler family

### ISSUE THREAD

**Issue by EvanMulawski** [EvanMulawski/FanControl.CorsairLink#67]
Add support for the following devices:

- Hydro H80i GT (`0c02`)
- Hydro H80i GT V2 (`0c08`)
- Hydro H80i Pro (`0c16`)
- Hydro H100i GT V2 (`0c09`)
- Hydro H100i GTX (`0c03`)
- Hydro H100i Pro (`0c15`)
- Hydro H110i GT V2 (`0c0a`)
- Hydro H110i GTX (`0c07`)
- Hydro H115i Pro (`0c13`)
- Hydro H150i Pro (`0c12`)

The Asetek Hydro AIOs use the same SI USB Xpress driver as the Flex USB PSU devices added in v1.3.0.

Progress:

- [x] Pro variants
- [x] V1 variants
- [x] V2 variants

**Comment by EvanMulawski** [comment]
@zenosisalive @cmoore-mayesh Can you run Fan Control with version v1.3.0-beta.4 of this plugin after installing the included driver and provide the `CorsairLink.log` file? Need to see if it already detects your devices.

**Comment by cmoore-mayesh** [comment]
Log attached.
[CorsairLink.log](https://github.com/EvanMulawski/FanControl.CorsairLink/files/12207950/CorsairLink.log)

**Comment by EvanMulawski** [comment]
@cmoore-mayesh Please try the attached build with debug logging enabled. To enable debug logging, set the `FANCONTROL_CORSAIRLINK_DEBUG_LOGGING_ENABLED` environment variable to `1` and restart Fan Control. Please provide the `CorsairLink.log` file after testing.

This build adds support for Asetek Pro AIOs only.

[FanControl.CorsairLink-AsetekDeviceExp-v20230730r001.zip](https://github.com/EvanMulawski/FanControl.CorsairLink/files/12209924/FanControl.CorsairLink-AsetekDeviceExp-v20230730r001.zip)

**Comment by cmoore-mayesh** [comment]
Appears to be having problems enumerating the device properly.
The SiUSBXp.dll is in the plugins folder properly and the env variable is properly set.
Attached is the log file as requested.

`2023-07-30T19:42:13.3253375Z [DBG] Corsair H150i Pro (1C2C03043D1712AB799502138DEE93AD): Connect
2023-07-30T19:42:13.3253375Z [DBG] Corsair H150i Pro (1C2C03043D1712AB799502138DEE93AD): Disconnect
2023-07-30T19:42:13.3308870Z [DBG] Corsair H150i Pro (1C2C03043D1712AB799502138DEE93AD): InitializeSpeedChannelStores
2023-07-30T19:42:13.3319126Z [DBG] Corsair H150i Pro (1C2C03043D1712AB799502138DEE93AD): SetChannelPower -1 50%
2023-07-30T19:42:13.3324345Z [DBG] Corsair H150i Pro (1C2C03043D1712AB799502138DEE93AD): SetChannelPower 0 50%
2023-07-30T19:42:13.3324345Z [DBG] Corsair H150i Pro (1C2C03043D1712AB799502138DEE93AD): SetChannelPower 1 50%
2023-07-30T19:42:13.3324345Z [DBG] Corsair H150i Pro (1C2C03043D1712AB799502138DEE93AD): SetChannelPower 2 50%
2023-07-30T19:42:13.3329623Z [DBG] Corsair H150i Pro (1C2C03043D1712AB799502138DEE93AD): WriteRequestedSpeeds
2023-07-30T19:42:13.3340303Z [DBG] Corsair H150i Pro (1C2C03043D1712AB799502138DEE93AD): SetPumpPower 50%
2023-07-30T19:42:13.3345561Z [DBG] Corsair H150i Pro (1C2C03043D1712AB799502138DEE93AD): WRITE: 3032
2023-07-30T19:42:13.3382088Z [WRN] Device Initialization: An error occurred initializing device 'Corsair H150i Pro (1C2C03043D1712AB799502138DEE93AD)' (\\?\usb#vid_1b1c&pid_0c12#7289_2.0#{3c5e1462-5695-4e18-876b-f3f3d08aaf18}):
2023-07-30T19:42:13.3382088Z [ERR] Device Initialization: 
Type: CorsairLink.SiUsbXpress.SiUsbXpressException
Message: Failed to read - data error.
Source: FanControl.CorsairLink
Stack Trace:
   at CorsairLink.SiUsbXpress.Driver.SiUsbXpressDevice.Read()
   at CorsairLink.Devices.HydroAsetekProDevice.WriteAndRead(Byte[] buffer)
   at CorsairLink.Devices.HydroAsetekProDevice.SetPumpPower(Byte percent)
   at CorsairLink.Devices.HydroAsetekProDevice.WriteRequestedSpeeds()
   at CorsairLink.Devices.HydroAsetekProDevice.Refresh()
   at CorsairLink.Devices.HydroAsetekProDevice.Connect()
   at FanControl.CorsairLink.CorsairLinkPlugin.FanControl.Plugins.IPlugin.Initialize()`

[CorsairLink.log](https://github.com/EvanMulawski/FanControl.CorsairLink/files/12209976/CorsairLink.log)

**Comment by EvanMulawski** [comment]
@cmoore-mayesh New build.

[FanControl.CorsairLink-AsetekDeviceExp-v20230730r002.zip](https://github.com/EvanMulawski/FanControl.CorsairLink/files/12210985/FanControl.CorsairLink-AsetekDeviceExp-v20230730r002.zip)

**Comment by cmoore-mayesh** [comment]
Appears to be somewhat functional.

The fan and pump tachs are WILD though.

![image](https://github.com/EvanMulawski/FanControl.CorsairLink/assets/18537993/15328481-ba9b-471d-8753-b0f04bfedc2e)

Log file attached.

[CorsairLink.log](https://github.com/EvanMulawski/FanControl.CorsairLink/files/12211045/CorsairLink.log)

**Comment by EvanMulawski** [comment]
@cmoore-mayesh This should fix the RPM readings.

[FanControl.CorsairLink-AsetekDeviceExp-v20230730r003.zip](https://github.com/EvanMulawski/FanControl.CorsairLink/files/12211114/FanControl.CorsairLink-AsetekDeviceExp-v20230730r003.zip)

**Comment by cmoore-mayesh** [comment]
Oh -- this is working so VERY nicely now.  RPM is accurate and responding as expected on pump and fan.
Curves applied are working as expected as well.

Many MANY thanks to you.  Now I can truly lose the bloated iCue software in its entirety.

[CorsairLink.log](https://github.com/EvanMulawski/FanControl.CorsairLink/files/12211155/CorsairLink.log)

**Comment by EvanMulawski** [comment]
@cmoore-mayesh Glad to hear it! Let me know if you experience any issues. This will be in v1.4.0-beta.1 after v1.3.0 is officially released.

**Comment by zenosisalive** [comment]
[CorsairLink.log](https://github.com/EvanMulawski/FanControl.CorsairLink/files/12237759/CorsairLink.log)

Hope that's ok

**Comment by EvanMulawski** [comment]
@zenosisalive That's expected. Only the Pro models are supported in the posted build - still working on the others.

**Comment by EvanMulawski** [comment]
@zenosisalive Please try the attached build with debug logging enabled. To enable debug logging, set the `FANCONTROL_CORSAIRLINK_DEBUG_LOGGING_ENABLED` environment variable to `1` and restart Fan Control. Please provide the `CorsairLink.log` file after testing.

[FanControl.CorsairLink-AsetekDeviceExp-v20230803r001.zip](https://github.com/EvanMulawski/FanControl.CorsairLink/files/12256763/FanControl.CorsairLink-AsetekDeviceExp-v20230803r001.zip)

**Comment by zenosisalive** [comment]
Sorry, I've looked but don't know where that setting/file is located

**Comment by EvanMulawski** [comment]
@zenosisalive The downloaded ZIP file needs to be unblocked first - follow [Installation](https://github.com/EvanMulawski/FanControl.CorsairLink#installation).

To enable debug logging, run the following in a Command Prompt window:

```
setx FANCONTROL_CORSAIRLINK_DEBUG_LOGGING_ENABLED 1
``` 

or use Windows search to launch the UI:

![image](https://github.com/EvanMulawski/FanControl.CorsairLink/assets/1044791/9b18ff6d-1606-4ca8-8022-4f2a3c702aac)

![image](https://github.com/EvanMulawski/FanControl.CorsairLink/assets/1044791/967d31ce-6b1d-4b82-9c7e-79fb8ab1d657)

and click **New** to add or **Edit** to change the selected environment variable.

**Comment by EvanMulawski** [comment]
@zenosisalive New build - this should fix the RPM readings. Let me know if you can control the fan and pump speeds.

[FanControl.CorsairLink-AsetekDeviceExp-v20230804r001.zip](https://github.com/EvanMulawski/FanControl.CorsairLink/files/12262700/FanControl.CorsairLink-AsetekDeviceExp-v20230804r001.zip)

**Comment by zenosisalive** [comment]
The RPM looks right and I seem to have pump control but not fan control
[CorsairLink.log](https://github.com/EvanMulawski/FanControl.CorsairLink/files/12262839/CorsairLink.log)

**Comment by zenosisalive** [comment]
Sets fan to max RPM on launch and doesn't respond to RPM slider

**Comment by EvanMulawski** [comment]
@zenosisalive New build.

[FanControl.CorsairLink-AsetekDeviceExp-v20230804r002.zip](https://github.com/EvanMulawski/FanControl.CorsairLink/files/12262908/FanControl.CorsairLink-AsetekDeviceExp-v20230804r002.zip)

**Comment by zenosisalive** [comment]
Still no Fan control
[CorsairLink.log](https://github.com/EvanMulawski/FanControl.CorsairLink/files/12263031/CorsairLink.log)
![FanScreen](https://github.com/EvanMulawski/FanControl.CorsairLink/assets/40674575/69e3800e-7f8a-438b-a7b0-ab81aa1351c2)

**Comment by EvanMulawski** [comment]
@zenosisalive Are you using the fan(s) that came with the device?

**Comment by cmoore-mayesh** [comment]
i cannot duplicate zeno's issue -- I have a SLIGHT revision of the same cooler on another PC.  Attached is the log -- not sure if this helpful or not.

[CorsairLink.log](https://github.com/EvanMulawski/FanControl.CorsairLink/files/12263531/CorsairLink.log)

**Comment by EvanMulawski** [comment]
@cmoore-mayesh Thanks - unfortunately that's a completely different device with a different communication protocol, even though the model name is similar.

**Comment by cmoore-mayesh** [comment]
Damn.  Was afraid of that.. I know this one is ancient but was hoping they didn't modify it too hard.  Good luck finding the issue.

**Comment by EvanMulawski** [comment]
@zenosisalive New build.

[FanControl.CorsairLink-AsetekDeviceExp-v20230804r003.zip](https://github.com/EvanMulawski/FanControl.CorsairLink/files/12264788/FanControl.CorsairLink-AsetekDeviceExp-v20230804r003.zip)

**Comment by zenosisalive** [comment]
There is only one fan plugged in but it is original. Behaviour was same under Corsair software and the fans are connected via a simple splitter. Sorry if that caused trouble :/

I have tested the latest build and all seems to be working correctly. The sensor nametext is also different to the prev builds.

[CorsairLink.log](https://github.com/EvanMulawski/FanControl.CorsairLink/files/12266525/CorsairLink.log)

**Comment by EvanMulawski** [comment]
@zenosisalive No problem at all, was just trying to get as much information as possible. Thanks for testing - going to release v1.4.0-beta.1 soon.

**Comment by EvanMulawski** [comment]
Completed in [v1.4.0-beta.1](https://github.com/EvanMulawski/FanControl.CorsairLink/releases/tag/v1.4.0-beta.1)
