### ISSUE TITLE
H115i Platinum not detected

### ISSUE THREAD

**Issue by jiboli** [EvanMulawski/FanControl.CorsairLink#70]
I'm geting this warning in the log file using the [v1.3.0-beta.4] version.

```
2023-07-31T22:06:59.3157235Z [WRN] Device Enumeration: Failed to enumerate SiUsbXpress devices.
2023-07-31T22:07:32.0381218Z [INF] HID Device Manager: Found 0 Corsair HID device(s)
```

I have the H115i Platinum AIO and NO corsair services installed and running, also, i'm using the .net 4.8 version of fancontrol.

Therefore, any sensors are loaded into Fancontrol

**Comment by EvanMulawski** [comment]
Hi @jiboli, the SiUsbXpress warning is currently only relevant if you have an AXi-series PSU.

All connected Corsair HID devices are listed in the log file regardless of compatibility with this plugin. Please ensure the device is connected via USB and is listed in Device Manager and/or [USBDeview](https://www.nirsoft.net/utils/usbdeview-x64.zip).

**Comment by jiboli** [comment]
USBDeview shows the following:

`H115i Platinum	WinUsb Device	Vendor Specific	Yes	No	No	No		7289_2.0	27/07/2023 14:17:38	27/07/2023 14:17:38	1b1c	0c13	1.00	WINUSB	ff	00	00		JIBOLI-NAVE				WINUSB	@winusb.inf,%WinUSB_SvcDesc%;Driver genérico para dispositivos USB	WinUsb.sys		WinUsb Device	H115i Platinum	64 mA	2.00	WinUsb Device	10.0.22621.580	WINUSB.NT	winusb.inf	USB\VID_1B1C&PID_0C13\7289_2.0	Removable, UniqueID					
`

**Comment by EvanMulawski** [comment]
That's very odd - PID `0c13` is the H115i Pro, not the H115i Platinum.

1. Uninstall this device/driver using USBDeview or Device Manager.
2. Follow the instructions provided in `Corsair-SiUsbXpress-Driver/README.txt` (in the v1.3.0-beta.4 release you downloaded) to install the correct driver.
3. Use the experimental version of this plugin that is compatible with the H115i Pro: https://github.com/EvanMulawski/FanControl.CorsairLink/issues/67#issuecomment-1657427633

Let me know if this works for you. Please provide the full `CorsairLink.log` if you encounter any issues (you can drag the log file into the comment box here).

**Comment by jiboli** [comment]
OK, it worked.

Apparently i have a H115i Pro, the more you know 😅.

but, in my defence, the USBDeview stil reports as a Platinum version.

Thank you for the help.

**Comment by EvanMulawski** [comment]
@jiboli If you encounter any issues, please let me know in #67 and provide your log file.
