### ISSUE TITLE
Corsair Fan Control Plugin is Missing

### ISSUE THREAD

**Issue by ApolloAdama007** [EvanMulawski/FanControl.CorsairLink#71]
![image](https://github.com/EvanMulawski/FanControl.CorsairLink/assets/141125315/76e927d7-b3e7-40c4-8132-190a6710c58b)

There's no DLL file for the corsair plugin available to download and extract. Please upload corsair fan control plugin.

**Comment by DfrostX** [comment]
This has been already answered. See below link:

https://github.com/EvanMulawski/FanControl.CorsairLink/issues/63
