### ISSUE TITLE
H100i Pro XT randomly disconnects and fails redetection

### ISSUE THREAD

**Issue by larz101** [EvanMulawski/FanControl.CorsairLink#76]
I love using this plugin to manage my fan behaviors (I'm running an ITX system that uses the AIO as an exhaust) but I'm having a strange bug where my H100i Pro XT disconnects randomly. I'm trying to make the switch from iCUE because of how I need the fans to respond to different sensors.

**Hardware:**
Ryzen 7 3700x
ASUS X570-I Strix
ASUS RTX 3090 TUF
and I have two Corsair devices connected: the H100i Pro XT (0c20) and a K70 LUX keyboard. None of them have any hardware/software RGB lighting profiles (and their default is set to be off). The H100i is set to the Quiet preset, and there are no custom fan curves set. Within Fan Control, the H100i is set at a fixed 30%.

**Software/Potential Conflicts:**
Windows 10

SignalRGB
- I matched the speed setting to Quiet.

HWinfo64 (installed) v7.60
- I disabled Corsair/Asetek support.

Fan Control v165 .NET 4.8
- I use the CorsairLink plugin (v1.3.0) and the HWinfo plugin (v1.3). I configured Fan Control to be the last software started after all monitoring programs.

I've attached a [CorsairLink.log](https://github.com/EvanMulawski/FanControl.CorsairLink/files/12270415/CorsairLink.log) for reference but most of it is full of detection errors despite the device still being shown as connected. For whatever reason, this bug doesn't seem to pop up on any logs since Windows doesn't make the USB disconnection sound, but software reports a timeout when trying to communicate with the AIO. When undetected by CorsairLink, the pump will still run and go to its default settings.

For troubleshooting, I've gone through most possibilities without any success. All of these were tried without iCUE installed.
- Disabled USB selective suspend
- Replugged SATA power
- Replugged microUSB/USB2.0 cable at both ends
- Reinstalled USB drivers
- Reinstalled chipset drivers
- Restarted and reinstalled H100i via Control Panel devices (Control Panel > Hardware and Sound > Devices and Printers)
- Restarted H100i via Device Manager through Human-Interface Devices
- Unchecked the box for "Allow the computer to turn off this device to save power"
_The H100i has a HID-compliant vendor-defined device and a USB Input Device component. I've tried configuring them with no success._
- Uninstalled and restarted USB hubs
- Updated and reinstalled H100i firmware
- Using my PC with and without SignalRGB installed
- Using my PC with and without HWinfo
- Having only FanControl with CorsairLink open
_I would try having none of these programs installed, but Windows wouldn't notify me that the AIO wasn't detected. There would be no way to know if the issue was still happening._

I've considered this being an unsolvable X570 USB dropout issue, but nothing else in the system suffers a performance hit or has stutter during the disconnect. The internal USB 2.0 header has no visible damage [and the H100i is isolated on its own USB root hub](https://github.com/EvanMulawski/FanControl.CorsairLink/assets/141586792/636fbbec-0aee-4e57-b646-c46a0a695bd6). Unfortunately, I don't have another internal USB2.0 header/device to isolate the issue. 

Right now, I'm running a _very_ janky solution to keep the H100i responding without restarting the whole system. Despite the incompatibilities, I installed iCUE and run it alongside all the previous software (Fan Control with CorsairLink/HWinfo plugins, HWinfo64, SignalRGB). For whatever reason, there aren't any disconnects when only using iCUE and it is the only program that has been able to keep the H100i detected after the disconnect notification from other software. If I have iCUE and everything else open, the disconnects still occur. However, after refreshing the sensor detection with iCUE open, Fan Control picks up the H100i again and everything works normally (RGB responds to effects and pump responds to Fan Control). However, it eventually disconnects and I have to refresh sensor detection. 

I'm not sure what else I can do to get this working, but I'm not yet convinced that the whole AIO is defective since iCUE somehow manages to circumvent the entire problem.

**Comment by EvanMulawski** [comment]
Does SignalRGB lose the connection as well?

**Comment by larz101** [comment]
Yes, it takes a restart of SignalRGB to fix the lighting.

**Comment by larz101** [comment]
Also want to add that if I do not restart SignalRGB, iCUE takes control over the lighting.

**Comment by EvanMulawski** [comment]
So... the microcontroller can lock up and iCUE will reboot the device if it happens:

https://forum.corsair.com/forums/topic/176494-corsair-h100i-platinum-se-randomly-stops-and-restarts/
https://forum.corsair.com/forums/topic/171275-hydro-h100i-connectingdisconnecting/

I might be able to do the same thing.

**Comment by EvanMulawski** [comment]
Closing in favor of #80.
