### ISSUE TITLE
Hydro H100i GT V2 not working using Plugin 1.4.0 Beta-1 

### ISSUE THREAD

**Issue by thul** [EvanMulawski/FanControl.CorsairLink#83]
Im running a Hydro H100i GT V2 (0c09) AOI and using the 1.4.0-Beta-1 version of the plugin. It is able to detect my RM750i, but not my AOI. It's using non-stock fans (Noctua), but i can't see pumps speed, temperatures of fan speeds at all. I'v added the CorsairLink.log file to the issue. In the logs there's no mention of my cooler at all

[CorsairLink.zip](https://github.com/EvanMulawski/FanControl.CorsairLink/files/12440892/CorsairLink.zip)

Any idea's why this might be the case?

**Comment by EvanMulawski** [comment]
Hi @thul, is the device listed in Device Manager and/or [USBDeview](https://www.nirsoft.net/utils/usbdeview-x64.zip)?

**Comment by thul** [comment]
![image](https://github.com/EvanMulawski/FanControl.CorsairLink/assets/1921331/40a3b639-960b-4b1a-9ad8-06632871458e)

It is listed in the Device Manager (Windows 11)

And using USBDeview i get the following info

![image](https://github.com/EvanMulawski/FanControl.CorsairLink/assets/1921331/b01f5831-97e9-468c-899f-b23c0661f389)

**Comment by thul** [comment]
@EvanMulawski That seemed to be the issue, i guess i missed the requirement of the that particular USB driver to be installed. I'll close this now
