### ISSUE TITLE
Issue with H150i Pro, device doesn't react after some time

### ISSUE THREAD

**Issue by GWEGWA** [EvanMulawski/FanControl.CorsairLink#87]
Hello,
So I've tried installing the last release - v1.4.0-beta.3 and this issue comes more often than before (in beta 1) 
What is happening is that FanControl loses control over my Corsair H150i Pro AiO. 
Commands and speeds doesn't update anymore. If I force manual to 100% nothing is happening.
In the logs, at the time I'm getting the issue, I start getting this message : 
2023-08-31T15:27:46.7239708Z [WRN] Plugin: Refresh skipped - refresh already in progress.
[CorsairLink.log](https://github.com/EvanMulawski/FanControl.CorsairLink/files/12487718/CorsairLink.log)
If I close FC and open it again, it will work again for about 20 minutes. 
Icue is installed but service is set to manual and Icue doesn't start with windows.

**Comment by EvanMulawski** [comment]
Hi @GWEGWA, I am working on this. Please see #79 and try [this build](https://github.com/EvanMulawski/FanControl.CorsairLink/issues/79#issuecomment-1694731296).

**Comment by EvanMulawski** [comment]
Fixed in [v1.4.0-beta.4](https://github.com/EvanMulawski/FanControl.CorsairLink/releases/tag/v1.4.0-beta.4)
