### ISSUE TITLE
Add support for Hydro series cooling devices

### ISSUE THREAD

**Issue by nordic-style** [EvanMulawski/FanControl.CorsairLink#9]
Is it possible to add Fan/Pump Control for the H60iRGBPROXT ?

The Pump has two fan connectors, one three pin fan connector for the pump speed (no control) and a USB connector for RGB and pump Control.

If you need more information i will try to support you.

Thanks and Cheers
[Corsair H60iRGBPROXT.txt](https://github.com/EvanMulawski/FanControl.CorsairLink/files/10535396/Corsair.H60iRGBPROXT.txt)

**Comment by nordic-style** [comment]
Sure - you can have remote access too, if you want.

**Comment by nordic-style** [comment]
@EvanMulawski If you need anything else - just tell me (I don't want to be a pain, but not that you're still waiting for something).

**Comment by EvanMulawski** [comment]
I'm currently researching/documenting the protocol for the Hydro devices. Just need some time 😂.

**Comment by EvanMulawski** [comment]
@nordic-style Please try the attached build. Follow the same [installation process](https://github.com/EvanMulawski/FanControl.CorsairLink/blob/main/README.md#installation).

Note: This build logs a lot of information to Fan Control's `log.txt` file. Please post this file if you encounter any problems.

[FanControl.CorsairLink-HydroDeviceExp-v20230205r001.zip](https://github.com/EvanMulawski/FanControl.CorsairLink/files/10613788/FanControl.CorsairLink-HydroDeviceExp-v20230205r001.zip)

**Comment by nordic-style** [comment]
Did not work:

What i did:


delete logfile
start Fan Control
search for sensors -> error msg
close Fan Control
post logfile

;)
[log.txt](https://github.com/EvanMulawski/FanControl.CorsairLink/files/10674006/log.txt)

**Comment by EvanMulawski** [comment]
@nordic-style Please try the attached build.

[FanControl.CorsairLink-HydroDeviceExp-v20230207r001.zip](https://github.com/EvanMulawski/FanControl.CorsairLink/files/10679691/FanControl.CorsairLink-HydroDeviceExp-v20230207r001.zip)

**Comment by nordic-style** [comment]
@EvanMulawski No more errors! - but:
No pump control
Control of the fans works but at 0% they still spin with - i would say 40 or 50 percent speed.
Weired RPM readings
[log.txt](https://github.com/EvanMulawski/FanControl.CorsairLink/files/10680384/log.txt)
<img width="554" alt="FanControl-002" src="https://user-images.githubusercontent.com/11313330/217393092-93c97601-e645-47f9-bc16-8fde2b2c8cf7.png">
<img width="1407" alt="FanControl-001" src="https://user-images.githubusercontent.com/11313330/217393096-afb58cb2-8888-4acc-9739-923d7adbc223.png">

**Comment by EvanMulawski** [comment]
Thanks for the info - I'm looking into the issues. Does the "Liquid Temp" sensor appear with a correct temperature in the "Temperature source" list for the graph curve?

**Comment by nordic-style** [comment]
@EvanMulawski  
The Liquid temp sensor readings are more like a signed int8 that is runnig from -127 to 128 and back to -127. The value changes every second, mostly in steps up to 12, but it also does not change for up to 10 seconds.

So no, no correct temperature.

**Comment by EvanMulawski** [comment]
@nordic-style New build: [FanControl.CorsairLink-HydroDeviceExp-v20230207r002.zip](https://github.com/EvanMulawski/FanControl.CorsairLink/files/10681679/FanControl.CorsairLink-HydroDeviceExp-v20230207r002.zip)

There is no pump control currently, so it's always set to the Balanced preset.

**Comment by nordic-style** [comment]
@EvanMulawski 
The temp sensor readings look good!
The pump rpm readings might also be fine - they are currently static at 1946 rpm
Fan control is still not working.
Can you  make the pump modes variable? If not - silent would be fine for me (and many others).

**Comment by EvanMulawski** [comment]
@nordic-style Can you post the log file again?

**Comment by nordic-style** [comment]
@EvanMulawski Sorry - i already created one but missed the upload.
Here is a fresh logfile and a sensor screenshot.

<img width="210" alt="FanControl-003" src="https://user-images.githubusercontent.com/11313330/217634265-739526a4-d520-41a6-920c-412b6a8d68c7.png">
[log.txt](https://github.com/EvanMulawski/FanControl.CorsairLink/files/10689338/log.txt)

**Comment by EvanMulawski** [comment]
@nordic-style New build: [FanControl.CorsairLink-HydroDeviceExp-v20230208r001.zip](https://github.com/EvanMulawski/FanControl.CorsairLink/files/10691367/FanControl.CorsairLink-HydroDeviceExp-v20230208r001.zip)

Should have fan control now.

Looking into pump control - will probably end up being a range for now, e.g.:

```
Fan Control Controller Value => Pump Preset
0-33% => Quiet
34-66% => Balanced
67-100% => Performance
```

Also looking into variable pump control.

**Comment by nordic-style** [comment]
@EvanMulawski 
I am missing the pump control panel. 
Fan Control does not work. The fans seem to run at 100%.

Attached a current screenshot and logfile.

[log.txt](https://github.com/EvanMulawski/FanControl.CorsairLink/files/10697105/log.txt)

<img width="903" alt="FanControl-005" src="https://user-images.githubusercontent.com/11313330/217813661-ed390440-efd1-46aa-ba99-faac180069be.png">

**Comment by EvanMulawski** [comment]
@nordic-style New build: [FanControl.CorsairLink-HydroDeviceExp-v20230209r001.zip](https://github.com/EvanMulawski/FanControl.CorsairLink/files/10703037/FanControl.CorsairLink-HydroDeviceExp-v20230209r001.zip)

No pump control yet - focusing on getting fan control working.

**Comment by nordic-style** [comment]
@EvanMulawski 
Nice work. Fan Control is working!
But: The fans never stop. I can control a NF-A14PWM from 300 to 1450 RPM (0-100% fanspeed)
And a tt toughfan 14 from 500 to 2000 RPM.

**Comment by EvanMulawski** [comment]
> But: The fans never stop. I can control a NF-A14PWM from 300 to 1450 RPM (0-100% fanspeed)
And a tt toughfan 14 from 500 to 2000 RPM.

I'll look into this - sounds like a safety feature.

---

Can you let me know if you have a fan connected for `Fan #1`? According to the log, you don't, but just want to make sure.

**Comment by nordic-style** [comment]
Yes - online one Fan Was connected.Von: Evan Mulawski ***@***.***>Gesendet: Freitag, 10. Februar 2023 19:40An: EvanMulawski/FanControl.CorsairLinkCc: nordic-style; MentionBetreff: Re: [EvanMulawski/FanControl.CorsairLink] Add support for Hydro series cooling devices (Issue #9) 

But: The fans never stop. I can control a NF-A14PWM from 300 to 1450 RPM (0-100% fanspeed)
And a tt toughfan 14 from 500 to 2000 RPM.

I'll look into this - sounds like a safety feature.

Can you let me know if you have a fan connected for Fan #1? According to the log, you don't, but just want to make sure.

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/EvanMulawski/FanControl.CorsairLink/issues/9#issuecomment-1426195055",
"url": "https://github.com/EvanMulawski/FanControl.CorsairLink/issues/9#issuecomment-1426195055",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by EvanMulawski** [comment]
@nordic-style New build: [FanControl.CorsairLink-HydroDeviceExp-v20230210r001.zip](https://github.com/EvanMulawski/FanControl.CorsairLink/files/10712211/FanControl.CorsairLink-HydroDeviceExp-v20230210r001.zip)

**Comment by nordic-style** [comment]
@EvanMulawski The Noctua does stop at 0% ! The Thermaltake sadly does not. I can reproduce this behavior with both FAN Ports. The Fans stay at the given speed and do not spin up after some seconds.

PS: the start voltage of the Thermaltake is 9V

**Comment by EvanMulawski** [comment]
@nordic-style Some fans will not stop even if the PWM signal tells them to - they will just stay at their minimum-rated RPM. I have a Corsair LL120 fan that behaves the same way, but my Noctua fans will actually stop.

I'll start working on the pump control.

**Comment by EvanMulawski** [comment]
@nordic-style New build: [FanControl.CorsairLink-HydroDeviceExp-v20230211r001.zip](https://github.com/EvanMulawski/FanControl.CorsairLink/files/10712719/FanControl.CorsairLink-HydroDeviceExp-v20230211r001.zip)

Pump control:

```
<= 33%  => Quiet
<= 67%  => Balanced
<= 100% => Performance
```

**Comment by nordic-style** [comment]
@EvanMulawski 
Thanks!
Pump Control:
Level1: 0-13 % -> 1950 RPM
Level2: 14-26 % -> 2333 RPM
Level3: 27%-100% -> 2670 RPM

"Silent Mode" with original Corsair tools were quieter imo
[log.txt](https://github.com/EvanMulawski/FanControl.CorsairLink/files/10714561/log.txt)

**Comment by EvanMulawski** [comment]
@nordic-style New build: [FanControl.CorsairLink-HydroDeviceExp-v20230211r002.zip](https://github.com/EvanMulawski/FanControl.CorsairLink/files/10714758/FanControl.CorsairLink-HydroDeviceExp-v20230211r002.zip)

This fixes the pump control range to match what I originally posted:

```
<= 33%  => Quiet
<= 67%  => Balanced
<= 100% => Performance
```

I can only send one of these presets to the device. The RPM readings in the log are consistent with what [other users are saying](https://www.reddit.com/r/Corsair/comments/kvc1dc/comment/gixmycb/?utm_source=share&utm_medium=web2x&context=3).

**Comment by nordic-style** [comment]
Great!
I can confirm that it is working as expext and that the RPM is the same as with the original software. If i close the case (Mjolnir) it is a little bit quieter and i do not recognize it anymore when i am sitting on the couch (it is part of my TV setup).

Thank you very much!

**Comment by EvanMulawski** [comment]
Just going to keep this open until I release it in an official build (without all the logging).

**Comment by EvanMulawski** [comment]
Completed in **v1.1.0-beta.1**:

https://github.com/EvanMulawski/FanControl.CorsairLink/releases/tag/v1.1.0-beta.1
