### ISSUE TITLE
Hydro Platinum device eventually reverts to defaults in v1.4.0-beta.4

### ISSUE THREAD

**Issue by EvanMulawski** [EvanMulawski/FanControl.CorsairLink#90]
Just left my system running for a few hours with v1.4.0-beta.4, I've now noticed the cooler's fans are running as slow as they possibly can. Totally ignoring my fan curves. 

I've restarted FanControl and they ramp up to the correct speeds set in my curves, but then they slowly fall down to ~600rpm. 

New log: 
[Log & Desktop Capture.zip](https://github.com/EvanMulawski/FanControl.CorsairLink/files/12498514/Log.Desktop.Capture.zip)

I've also attached a screen capture of what happens when I load FanControl with v1.4.0-beta.4. You can see the front fans ramp up to their correct speeds, then they slowly go back down to ~600rpm as described above. 

I have reverted back to the build you sent above (called v20230831r001.zip) and all fans respond perfectly.

_Originally posted by @Meh7991 in https://github.com/EvanMulawski/FanControl.CorsairLink/issues/47#issuecomment-1702781250_

**Comment by EvanMulawski** [comment]
@Meh7991 Please try this build.
[FanControl.CorsairLink-HydroPlatinumIssue90-v20230901r001.zip](https://github.com/EvanMulawski/FanControl.CorsairLink/files/12500091/FanControl.CorsairLink-HydroPlatinumIssue90-v20230901r001.zip)

**Comment by Meh7991** [comment]
> Please try this build. [FanControl.CorsairLink-HydroPlatinumIssue90-v20230901r001.zip](https://github.com/EvanMulawski/FanControl.CorsairLink/files/12500091/FanControl.CorsairLink-HydroPlatinumIssue90-v20230901r001.zip)

@EvanMulawski that build does the exact same thing, reverting to ~600rpm.

**Comment by EvanMulawski** [comment]
@Meh7991 Can you enable debug logging and post the log when you get a chance?

**Comment by Meh7991** [comment]
Sure, here's a 5 minute log when using the build you posted above: 
[Log.zip](https://github.com/EvanMulawski/FanControl.CorsairLink/files/12500215/Log.zip)

**Comment by EvanMulawski** [comment]
@Meh7991 New build.
[FanControl.CorsairLink-HydroPlatinumIssue90-v20230901r002.zip](https://github.com/EvanMulawski/FanControl.CorsairLink/files/12500403/FanControl.CorsairLink-HydroPlatinumIssue90-v20230901r002.zip)

**Comment by Meh7991** [comment]
Seems stable now! Do you want me to send over any more logs?

**Comment by EvanMulawski** [comment]
@Meh7991 All good.

Fixed in [v1.4.0-beta.5](https://github.com/EvanMulawski/FanControl.CorsairLink/releases/tag/v1.4.0-beta.5)
