### ISSUE TITLE
Hydro Platinum Elite models not responding

### ISSUE THREAD

**Issue by EvanMulawski** [EvanMulawski/FanControl.CorsairLink#93]
### Discussed in https://github.com/EvanMulawski/FanControl.CorsairLink/discussions/92

<div type='discussions-op-text'>

<sup>Originally posted by **HaidaLaOBere** September  1, 2023</sup>
I installed the plugin as instructed and installed (I hope) corsiarsiusbxp.inf (it gave me a error "Certificate was explicitly revoked by it's issuer) 
After a while I got propped with this in corsairlink.log ( I keep getting the same error except for readCrcByte and readBufferCrcResult)

[CorsairLink.log](https://github.com/EvanMulawski/FanControl.CorsairLink/files/12501475/CorsairLink.log)

Can someone help me? </div>

**Comment by EvanMulawski** [comment]
@HaidaLaOBere Please try the attached build and post the CorsairLink.log file after testing (you can delete your current log file).
[FanControl.CorsairLink-HydroPlatinumIssue93-v20230901r001.zip](https://github.com/EvanMulawski/FanControl.CorsairLink/files/12502700/FanControl.CorsairLink-HydroPlatinumIssue93-v20230901r001.zip)

**Comment by Profetorum** [comment]
Type: CorsairLink.CorsairLinkDeviceException
Message: Checksum failure.
Source: FanControl.CorsairLink
Stack Trace:
   in CorsairLink.Devices.HydroPlatinumDevice.SendCommand(Byte command, ReadOnlySpan`1 data)
   in CorsairLink.Devices.HydroPlatinumDevice.ReadState()
   in CorsairLink.Devices.HydroPlatinumDevice.Refresh()
   in FanControl.CorsairLink.CorsairLinkPlugin.Refresh()
   
   
[CorsairLink.log](https://github.com/EvanMulawski/FanControl.CorsairLink/files/12504592/CorsairLink.log)

This is the very first with the version above, going to update if i get more errors

**Comment by EvanMulawski** [comment]
@Profetorum Thanks! I will publish a new beta release with this fix shortly.

**Comment by EvanMulawski** [comment]
Fixed in [v1.4.0-beta.6](https://github.com/EvanMulawski/FanControl.CorsairLink/releases/tag/v1.4.0-beta.6)

**Comment by HaidaLaOBere** [comment]
Yep I can confirm it's fixed, thank you for the quick work
