### ISSUE TITLE
H150i Elite RGB : CorsairLink.CorsairLinkDeviceException , Communication failure

### ISSUE THREAD

**Issue by Profetorum** [EvanMulawski/FanControl.CorsairLink#94]
[CorsairLink.log](https://github.com/EvanMulawski/FanControl.CorsairLink/files/12503788/CorsairLink.log)

Using a H150i Elite RGB AIO.
Occasionally getting a popup window notifying there are errors

**Comment by EvanMulawski** [comment]
Hi @Profetorum, please see #93.
