### ISSUE TITLE
SignalRGB compatibility

### ISSUE THREAD

**Issue by larz101** [EvanMulawski/FanControl.CorsairLink#95]
Hi again,

The latest 1.4.0-beta.5 release has mostly solved the disconnection issues that I posted in #76 with my H100i Pro XT. I've been able to uninstall iCUE and have everything running mostly stable. However, I've been able to narrow down the last bit of disconnection to be caused by SignalRGB. Whenever it is open (regardless if the H100i is enabled or disabled via Devices), the CorsairLink plugin still spits out the same "Multiple errors detected" message and the H100i becomes unresponsive until I do a cold boot. It's the same error I posted in #76.

I saw that the compatibility section was updated, but I was confused with what was meant by the "Commander only" note. I don't mean to add a redundant issue if SignalRGB is already known to be causing problems with the new builds, but I wanted to make sure this was known.

**Comment by EvanMulawski** [comment]
Hi @larz101, a SignalRGB developer recently informed me that they only use the mutex/lock that synchronizes device communication on the Commander devices - non-Commander devices are not officially compatible with other software while SignalRGB is running. I am not sure if or when they will be implementing this, but I would encourage you (and anyone else affected by this) to request this via their forum and link them here.

In addition, I am planning to contribute to OpenRGB to add this compatibility. (A recent commit has implemented this for Commander CORE devices.)

References:
- https://github.com/EvanMulawski/FanControl.CorsairLink/issues/47#issuecomment-1699964758
- https://github.com/EvanMulawski/FanControl.CorsairLink/issues/47#issuecomment-1701479649

**Comment by DfrostX** [comment]
Hopefully they will accept to merge your commit. Sadly the develloper is very Linux focus and often will snob Windows/ other software compatibility changes, mentionning this is Windows specific stuff that is not needed on Linux.

Regardless, thanks for your hard work, it is very appreciated!

**Comment by chjohans** [comment]
Thank you @EvanMulawski, it's great to see that you will contribute to OPenRGB to add compatib ility for more CorsairLink products than just the COmmander device(s).

Any idea when this could be implemented? Eg can I follow the status of this somewhere (I've searched - but didn't find..)?

**Comment by jhiggins** [comment]
I am using SignalRGB with the new Corsair LINK devices and I am seeing these errors.  Everything seems to be working correctly, but I am kind of assuming is errors are because of the same mutex.  If not, I can open a separate issue.  CorsairLink.log from today is attached.

[CorsairLink.log](https://github.com/EvanMulawski/FanControl.CorsairLink/files/13593321/CorsairLink.log)

**Comment by EvanMulawski** [comment]
SignalRGB version `2.3.45` implements the well-known mutex for Hydro Platinum AIOs.
