### ISSUE TITLE
HydroPlatinum Checksum Failure

### ISSUE THREAD

**Issue by Profetorum** [EvanMulawski/FanControl.CorsairLink#97]
Type: CorsairLink.CorsairLinkDeviceException
Message: Checksum failure.
Source: FanControl.CorsairLink
Stack Trace:
   in CorsairLink.Devices.HydroPlatinumDevice.SendCommand(Byte command, ReadOnlySpan`1 data)
   in CorsairLink.Devices.HydroPlatinumDevice.ReadState()
   in CorsairLink.Devices.HydroPlatinumDevice.Refresh()
   in FanControl.CorsairLink.CorsairLinkPlugin.Refresh()
Data:
    writeBuffer: 003F08FF00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF32
    readBuffer: 00C1C01207008E266D2413034FE8034F3D02034FE8034F3D0201BF0000BFCC0900000000000000034FFFFF4F530201F25000052D3237417124000000000000001F

[CorsairLink.log](https://github.com/EvanMulawski/FanControl.CorsairLink/files/12505832/CorsairLink.log)

Using beta 6 from yesterday - h150i elite

**Comment by EvanMulawski** [comment]
These errors will occur occasionally under normal operation; SignalRGB logs these as well. This isn't a cause for concern unless multiple errors occur consecutively. I could wait and retry the read, but the refresh interval is one second anyway.
